<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Betslip_stake_input slip_stake_single</name>
   <tag></tag>
   <elementGuidId>575c0497-5f65-4bd3-8643-d3ab02136cc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='10']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.stake_input.slip_stake_single</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4edf7cc9-52e5-46ad-949b-f8be33034ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>08c3b99b-1725-4d76-a6d5-aa2bd9c9da8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>fc6d8d5d-39b5-426c-ada1-c544fc9045d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>1cae37a3-868b-47d6-918f-aa8a0f06ead9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>.01</value>
      <webElementGuid>ca9764ea-2f8e-44bd-b1c1-748ce8dc6b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>clickevent(this)</value>
      <webElementGuid>a6d294ce-4674-465d-a52a-87bbb89f8b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>stake_input slip_stake_single</value>
      <webElementGuid>17d3b85a-0f50-4c18-89fd-d9c7db172914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>472ac392-ad67-4ce4-a5c1-5df487732c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zone-container&quot;)/div[@class=&quot;bet_slip_section  betslip_logged_in&quot;]/div[@class=&quot;bet_slip_toggle_sec desktp_bet_slip open&quot;]/div[@class=&quot;bet_slip_toggle_body bet_slip_open&quot;]/div[@class=&quot;tab_overflow&quot;]/div[@class=&quot;slip_tab_content&quot;]/div[@class=&quot;tab-content active slip_contents&quot;]/div[@class=&quot;bet_slip_cnt_main_sec&quot;]/div[@class=&quot;bet_slip_main_sec    slip_selections&quot;]/div[@class=&quot;bet_slip_row_main af_log_bet&quot;]/div[@class=&quot;bet_slip_row user_selection cls_sp_bslip&quot;]/div[@class=&quot;slip_input_sec&quot;]/div[@class=&quot;input_rgt single_stake_div&quot;]/input[@class=&quot;stake_input slip_stake_single&quot;]</value>
      <webElementGuid>15c1b368-d3ab-4285-9179-4ce68a77c8ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='10']</value>
      <webElementGuid>c458dc9b-6415-442d-a676-da2e84050c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zone-container']/div[3]/div/div/div[2]/div/div/div[2]/div/div/div/div[3]/div[2]/input</value>
      <webElementGuid>5a6a7087-9d8d-4dc8-9e88-d6e5103187bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>c28c30a5-8c36-4f2a-8ac5-5e2198cb7813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number']</value>
      <webElementGuid>8d46bbcd-1689-42a4-99ea-2e091829e154</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
