<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Long Term Bets</name>
   <tag></tag>
   <elementGuidId>e348bfbb-d772-466f-87c9-28bfbb7fedc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='yui_3_5_0_1_1638767565034_97204']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#yui_3_5_0_1_1638767565034_97204</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>72379ae5-d410-4733-8b56-f90b9d57ebd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sportName</value>
      <webElementGuid>28b45546-ce8d-4f33-9ba7-d72fd3213e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yui_3_5_0_1_1638767565034_97204</value>
      <webElementGuid>94f9dcae-98ca-4808-b954-e2c442a84b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Long Term Bets</value>
      <webElementGuid>e5b59cf4-4f66-41e2-84c0-7936ec6a98cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_5_0_1_1638767565034_95659&quot;)/li[@class=&quot;ui-clickselect&quot;]/a[@class=&quot;ui-gtm-click-defer&quot;]/span[@id=&quot;yui_3_5_0_1_1638767565034_97204&quot;]</value>
      <webElementGuid>3c6218e4-e05f-457b-ba6a-2e450f098e7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='yui_3_5_0_1_1638767565034_97204']</value>
      <webElementGuid>41a6ff73-f476-46af-80ca-28fd0ee41285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='yui_3_5_0_1_1638767565034_95659']/li[4]/a/span[2]</value>
      <webElementGuid>322aae84-70cb-4f33-9a5b-040658f20316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In-Play'])[1]/following::span[2]</value>
      <webElementGuid>2c30f25a-6675-4aa5-91bf-fed9d3681232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/following::span[4]</value>
      <webElementGuid>a7f7810e-2c64-4e73-bd3d-bd682edfc856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promotions'])[1]/preceding::span[2]</value>
      <webElementGuid>291e6900-6458-4927-b8e6-9a25676e2eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Long Term Bets']/parent::*</value>
      <webElementGuid>27090dff-5a83-4101-a833-47201e4844e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/span[2]</value>
      <webElementGuid>bb96b420-e1b4-42fc-95db-4e97a92c6c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'yui_3_5_0_1_1638767565034_97204' and (text() = 'Long Term Bets' or . = 'Long Term Bets')]</value>
      <webElementGuid>879a4c5b-32a9-49db-8025-3ffebb14b147</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
