<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Estonia</name>
   <tag></tag>
   <elementGuidId>f419ea0b-b71d-4008-8327-47d1a68bf63f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mod-minimarketview-1056']/div[2]/ul/li/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.runner-name.outcomeDescription</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0d2c2e4d-3792-4c4a-b884-b48610f9e706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>runner-name outcomeDescription</value>
      <webElementGuid>1b081e97-a7bb-445c-86b0-abe949b6b204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-otname</name>
      <type>Main</type>
      <value>Estonia</value>
      <webElementGuid>b47764fd-631a-492e-a109-4ade58710d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Estonia</value>
      <webElementGuid>a724ac67-d28d-47b9-ba9e-9b9b9bc1108c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mod-minimarketview-1056-container&quot;)/div[@id=&quot;mod-minimarketview-1056&quot;]/div[@class=&quot;minimarketview-content minimarket-MATCH_ODDS-286580488 ui-market ui-market-open cls_et_details cl_ui-market&quot;]/ul[@class=&quot;runner-list3 minimarketview-1056 sb_all_outcome_container kssrr___ext&quot;]/li[@class=&quot;runner-item sb_outcome_box sb-odm accept_tickets&quot;]/span[@class=&quot;runner-name outcomeDescription&quot;]</value>
      <webElementGuid>05e13a2b-b153-416a-a0c0-dde153beddda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mod-minimarketview-1056']/div[2]/ul/li/span</value>
      <webElementGuid>be2a04cb-758d-44a2-af71-663526000259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In-Play'])[2]/following::span[1]</value>
      <webElementGuid>901b70cb-a016-434d-a29e-43a35e64105e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Will Go In-Play'])[1]/following::span[2]</value>
      <webElementGuid>c19808b0-a954-4398-970d-c114462d422f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/preceding::span[2]</value>
      <webElementGuid>f9cbfbc0-cece-4871-a485-4497ec4df9ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Finland'])[1]/preceding::span[3]</value>
      <webElementGuid>52a7e06d-b01a-4c44-9b10-4dc0bc3e930e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Estonia']/parent::*</value>
      <webElementGuid>101065c5-2481-47e1-86fe-6923716bb8ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/span</value>
      <webElementGuid>20df01b1-7820-4d8c-bc76-c50bf9f84b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Estonia' or . = 'Estonia')]</value>
      <webElementGuid>1289b5c6-ea8c-462c-8617-c1c88273a7bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
