<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ukraine</name>
   <tag></tag>
   <elementGuidId>8eba225c-bede-4fb9-8c52-45d333ab3afe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='mod-minimarketview-1056']/div[2]/ul/li/span)[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>92bddc99-5537-4b1d-86e8-11be39dab4cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>runner-name outcomeDescription</value>
      <webElementGuid>d67f1d1a-1e73-49b7-9d3e-1df2095a0aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-otname</name>
      <type>Main</type>
      <value>Ukraine</value>
      <webElementGuid>98e89782-924e-49dd-828e-b0e8ffb68dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ukraine</value>
      <webElementGuid>6b05835a-1db7-4e6e-9ec0-4167ab26ae13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mod-minimarketview-1056-container&quot;)/div[@id=&quot;mod-minimarketview-1056&quot;]/div[@class=&quot;minimarketview-content minimarket-MATCH_ODDS-286580488 ui-market ui-market-open cls_et_details cl_ui-market&quot;]/ul[@class=&quot;runner-list3 minimarketview-1056 sb_all_outcome_container kssrr___ext&quot;]/li[@class=&quot;runner-item sb_outcome_box sb-odm accept_tickets&quot;]/span[@class=&quot;runner-name outcomeDescription&quot;]</value>
      <webElementGuid>83245385-da46-4ceb-b680-9760d69a31c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='mod-minimarketview-1056']/div[2]/ul/li/span)[5]</value>
      <webElementGuid>4a851fef-f526-4fcb-9cfa-d4c8100d55ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In-Play'])[3]/following::span[1]</value>
      <webElementGuid>d5ef34ab-e20a-4b0d-a369-2854f0c30cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Will Go In-Play'])[2]/following::span[2]</value>
      <webElementGuid>8ac37d1a-4d38-41b6-8a42-815541db25c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[5]/preceding::span[2]</value>
      <webElementGuid>39e1b173-f6ea-4349-8b02-9c7a94e5230f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iceland'])[1]/preceding::span[3]</value>
      <webElementGuid>79b12665-3451-4d42-9b14-ccfa235301c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ukraine']/parent::*</value>
      <webElementGuid>917a2e1d-8c7f-4b57-8400-ead8b8500aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/ul/li/span</value>
      <webElementGuid>4d2e92af-08f7-4e9f-859d-bf346e3c8b3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Ukraine' or . = 'Ukraine')]</value>
      <webElementGuid>fda1ba98-f6d0-4717-b5c0-1ffdf1e20904</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
