<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Yes</name>
   <tag></tag>
   <elementGuidId>4d7ff0d3-210c-42a4-92ae-edc5915c6197</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mod-minimarketview-1056']/div[2]/ul/li/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.runner-name.outcomeDescription</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>95782e97-a582-4a63-9a80-e4e543abff0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>runner-name outcomeDescription</value>
      <webElementGuid>275b42dd-00c7-4273-9fa7-6f2b29387e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-otname</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>112505c6-54a7-4c29-98d9-bf2db084bf0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>a85fcd33-9225-4d04-916b-414fc66d3599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mod-marketgroups-1091&quot;)/div[@class=&quot;marketgroups-list-container cl_marketgroup&quot;]/div[2]/div[@class=&quot;updated-minimarkets cls_evtdetails&quot;]/div[@class=&quot;list-minimarkets ui-inplay ui-event mainContentsBox eventBlock_srseason106479&quot;]/div[@id=&quot;mod-minimarketview-1056-container&quot;]/div[@id=&quot;mod-minimarketview-1056&quot;]/div[@class=&quot;minimarketview-content minimarket-MATCH_ODDS-286580488 ui-market ui-market-open cls_et_details cl_ui-market&quot;]/ul[@class=&quot;runner-list3 minimarketview-1056 sb_all_outcome_container kssrr___ext&quot;]/li[@class=&quot;runner-item sb_outcome_box sb-odm accept_tickets&quot;]/span[@class=&quot;runner-name outcomeDescription&quot;]</value>
      <webElementGuid>d70f6dc8-0056-4a84-b381-a668255ac9dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mod-minimarketview-1056']/div[2]/ul/li/span</value>
      <webElementGuid>29aa2b96-5b48-4528-9a38-01c5156cc129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In-Play'])[2]/following::span[1]</value>
      <webElementGuid>d488c852-0a5e-4abc-8f0e-43cc7d7eda68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Will Go In-Play'])[1]/following::span[2]</value>
      <webElementGuid>4ad45598-319b-4941-8718-900462e19620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/preceding::span[2]</value>
      <webElementGuid>98150f70-b8a2-47bd-8aa8-263b7e0c1540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::span[3]</value>
      <webElementGuid>4ac02825-f0d1-461d-90a9-6b8bdcf866d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Yes']/parent::*</value>
      <webElementGuid>2ae9216d-5021-451b-a8c0-c663f3e0bd09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/span</value>
      <webElementGuid>178fd907-677b-4bcd-a2af-a6f0ca066e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>63793a50-307c-4fb8-bd93-13a7f895f87e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
