<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Refer and Earn_iframePage</name>
   <tag></tag>
   <elementGuidId>9b9e911e-c52a-453d-b18d-b23409fdc48d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframePage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iframePage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ee2aa17b-4841-4c43-a914-9a45f16caec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframePage</value>
      <webElementGuid>237e090e-a14d-4a3d-9033-5ac4ac05e42f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>iframePage</value>
      <webElementGuid>e6e151b8-4951-437c-bf09-b8fcd114708e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-920</value>
      <webElementGuid>4951b6cd-3b31-41d9-a043-bfaf836a20e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a39fd8fd-5faa-4767-9896-aade17b8db26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://haboom.com/d/exch_bethistory_sr</value>
      <webElementGuid>38e7b728-e863-46ea-8eab-d4fb32a4f8da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bis_size</name>
      <type>Main</type>
      <value>{&quot;x&quot;:345,&quot;y&quot;:148,&quot;w&quot;:1213,&quot;h&quot;:920,&quot;abs_x&quot;:345,&quot;abs_y&quot;:148}</value>
      <webElementGuid>17f3df20-505e-47c7-b6cd-f0997bd91e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bis_id</name>
      <type>Main</type>
      <value>fr_6nunrdodrod4o225ezhs2m</value>
      <webElementGuid>621e3cb5-02e0-4e32-b742-0c89c790b94b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bis_depth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>aa54746d-de60-4b92-9445-854afa24afda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bis_chainid</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4bbb5cee-2050-4e5d-94df-a675fdad921d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>resizeIframe(this)</value>
      <webElementGuid>5c55a4dd-e781-452d-b5fe-3d2b027bdc37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframePage&quot;)</value>
      <webElementGuid>05399d35-c961-49b0-a3d2-ac5706bcdf9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframePage']</value>
      <webElementGuid>02e44302-ee8e-4290-8bc3-1d4b0b1f2ec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mod-iframe-53648']/div/div/div/iframe</value>
      <webElementGuid>f6ce8756-f746-4f04-a1fb-3fb30b5a0769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>fcd1c435-3cea-416a-a786-e77bbca39ca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframePage' and @name = 'iframePage' and @src = 'https://haboom.com/d/exch_bethistory_sr']</value>
      <webElementGuid>c999e439-1d8f-47f7-a3b4-29eaeacaff53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
