<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Help_submitLogForm</name>
   <tag></tag>
   <elementGuidId>57d8158c-6726-475c-ae58-f58f2eb99c5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='submitLogForm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#submitLogForm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ecfc0589-6253-4157-8b35-eba470339ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>da2632b9-b9b1-406e-a577-c2baba16f93b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>head_login</value>
      <webElementGuid>042b7e20-92d0-4c5b-bb5f-132abfcb8b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ssc-cta ssc-cta-simple</value>
      <webElementGuid>f4bc4c49-92ce-4fbf-8afd-2427bc92d181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Log In</value>
      <webElementGuid>a53213a2-6f90-433a-a46e-aa3dec23e6dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>checkLogin(this)</value>
      <webElementGuid>40fe41c3-3c24-4df6-9420-1bc97ac78c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submitLogForm</value>
      <webElementGuid>99bd98a8-326d-4cf2-82f5-d703f0340419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submitLogForm&quot;)</value>
      <webElementGuid>97537a6a-7735-46ac-8659-4b61d9eab807</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='submitLogForm']</value>
      <webElementGuid>6f218bab-9f3d-4531-978d-ef39a115c570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='head_login']/div[2]/input</value>
      <webElementGuid>5f40b75d-1c2b-49bf-bd5a-a8846c03f2ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>c3983a93-9251-4f49-baed-543b93083ccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'submitLogForm']</value>
      <webElementGuid>a703d272-784c-4fdf-98e3-39deb283d6e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
