<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Deposit</name>
   <tag></tag>
   <elementGuidId>69c5b86e-f849-4cf2-b40c-7a88e5ce6fed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='continueButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#continueButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a0c8737d-5ba7-4484-a455-9ce38466df02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>96cd7b69-6e5f-40f2-85ac-d7312f6a0809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>ec87c03e-1ad7-4799-8b95-e1e37f3c219a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnSubmit</value>
      <webElementGuid>7f70f49a-4747-4fde-a16f-8af92399fe5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>continueButton</value>
      <webElementGuid>9f749361-2f67-461d-a939-3b67b51c7add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>continue</value>
      <webElementGuid>60ad09d7-91e4-4f08-b85a-220a32267370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                   Deposit
                                 </value>
      <webElementGuid>14021e64-a9a9-4d43-bec8-69b5f1a2801c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;continueButton&quot;)</value>
      <webElementGuid>89def8e1-a44e-47d3-8b2e-d6d61191ca99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/My Account_Payment/Deposit page/instant deposit</value>
      <webElementGuid>6f9c3946-2cfa-4871-826f-6c106ca676ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='continueButton']</value>
      <webElementGuid>1d88ad93-1cd2-4853-bbf6-a2ecdc4710ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='amount_section_wrapper']/div[3]/div[3]/div[2]/button</value>
      <webElementGuid>ba9271b5-d5f1-40e7-b69b-020148551803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹'])[1]/following::button[1]</value>
      <webElementGuid>58a35756-1582-41e0-aa9f-d69a134e4752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='or'])[2]/following::button[1]</value>
      <webElementGuid>6c0a9ef6-419e-4e6c-ac53-581b1483269e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'continueButton', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>2256730d-d5aa-4d39-8eab-5f82b7950893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Deposit']/parent::*</value>
      <webElementGuid>69554eee-779a-4c13-8d95-cbd7882ef364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>4bf4d392-ffab-40f0-9a71-214e91145bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'btnSubmit' and @id = 'continueButton' and (text() = '
                                   Deposit
                                 ' or . = '
                                   Deposit
                                 ')]</value>
      <webElementGuid>3cbcb454-aafe-4a93-818c-32a790133571</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
