<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input instant method</name>
   <tag></tag>
   <elementGuidId>4e158a52-9ba7-44ad-b6cd-9cbf264be94f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='depositInstantamount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#depositInstantamount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4a2fe23-73f9-423b-a077-0ced47720836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>6ee073db-801e-442a-890d-de054226fbcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>37c50124-a023-47e1-99cf-96b3350b8b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>depositInstantamount</value>
      <webElementGuid>15784b85-7831-4175-ba51-75e86daf80f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>amount open_amount_input </value>
      <webElementGuid>ff7d8cfd-308a-45c7-b394-1649fa8a9783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>583a4d58-c114-4d5e-8850-6db3a9f3b9fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item_amount_1</value>
      <webElementGuid>ae5aebd0-226c-4509-8cb7-00ec3ae72b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>ffef2c6e-7966-4d43-a733-dcf6e73cd83f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>validateNumberLatest(this)</value>
      <webElementGuid>22ba3fd0-3191-463e-93b2-2acbb80741ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;depositInstantamount&quot;)</value>
      <webElementGuid>3f84a008-bf40-4378-8d43-c3678f017eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/My Account_Payment/Deposit page/deposit input field/input field</value>
      <webElementGuid>0da120bb-9757-4d9f-a652-e50a296d3ba3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='depositInstantamount']</value>
      <webElementGuid>8d9ada65-867c-4ae5-8954-982ea31ee512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='amount_section_wrapper']/div[3]/div[3]/div/div/input</value>
      <webElementGuid>ca933abb-8754-4284-8e4c-20f09a2840a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ee251948-c705-4c9c-9b4d-d1fb15230522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'depositInstantamount' and @name = 'item_amount_1']</value>
      <webElementGuid>ff4c7c35-75b4-4fbf-8611-8b1f7285785e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
