<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input field</name>
   <tag></tag>
   <elementGuidId>dbf86810-a648-4177-962b-594d38529522</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframePage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iframePage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>1c0bc889-bf87-4b2e-94b4-0aa067188048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframePage</value>
      <webElementGuid>b8425045-5cac-4f34-9e7d-4b43d9705e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>iframePage</value>
      <webElementGuid>ff7ffe18-e08d-44df-936e-8c50144529a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-1060</value>
      <webElementGuid>350a4f57-d0f0-4d7b-9cb2-5bb2cddc4297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>eea52e57-5c10-4483-8933-993dd368a4ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://haboom.com/d/deposit_sr</value>
      <webElementGuid>7d7b7e20-d982-4f3f-8e87-a6d6ebfea499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bis_depth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dffd3e15-2e80-44ac-a225-5f54a9fea80f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bis_chainid</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5807289b-8d0c-4c7e-8f0b-c348fc3ac94f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>214e3e55-8d7d-446b-b610-6ed0e5c60344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>resizeIframe(this)</value>
      <webElementGuid>33396b6e-db31-4c95-bca4-3f59707e6c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframePage&quot;)</value>
      <webElementGuid>1ad16e41-4d99-4d6f-a7a1-4a9762f035e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframePage']</value>
      <webElementGuid>f692ee91-503b-4681-bbec-168719e64fda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mod-iframe-52107']/iframe</value>
      <webElementGuid>4be0efad-2da9-4441-a2f7-2e9237a22aee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>f8be3510-8356-4b62-ad58-04c172403112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframePage' and @name = 'iframePage' and @src = 'https://haboom.com/d/deposit_sr']</value>
      <webElementGuid>43c510c0-f8e3-4dda-8e12-7850980dede0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
