<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>instant deposit</name>
   <tag></tag>
   <elementGuidId>e0b89f98-c86b-4927-8457-4548cc45c4e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframePage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iframePage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>de8b0703-0b9c-43db-bf47-0a61b244de6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframePage</value>
      <webElementGuid>26f42fd4-ea51-4a21-bf34-5bce31d576f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>iframePage</value>
      <webElementGuid>6959bb59-c400-42e5-94dc-541af6a21459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-1060</value>
      <webElementGuid>f7ad1161-244b-4a27-9199-de7c05ed7db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5c8f1aac-ddcb-48d1-ad30-05568e651f23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://haboom.com/d/deposit_sr</value>
      <webElementGuid>f7b42680-c94a-41a5-85bc-da8555c91fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bis_depth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b730171f-b34a-4fa2-a7db-73e21846129b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bis_chainid</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5615dc5a-8386-4d31-899f-de71a77d37d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>01b4c840-4bf8-4a6d-af30-0a56637c11e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>resizeIframe(this)</value>
      <webElementGuid>0c71c431-be25-426c-9ab9-48788f305151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframePage&quot;)</value>
      <webElementGuid>ad6ee1b0-981a-4566-b94d-62bff600339f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframePage']</value>
      <webElementGuid>5e2d72c8-d5f2-43e6-84e7-588d17ef4b8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mod-iframe-52107']/iframe</value>
      <webElementGuid>67afbce6-9f2f-4d63-81b6-3348553cddee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>447dba8c-bf90-4ba1-84f5-602d8b193785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframePage' and @name = 'iframePage' and @src = 'https://haboom.com/d/deposit_sr']</value>
      <webElementGuid>5a9d0d73-b0ae-4801-88b8-30ee50755afa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
