<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>instant</name>
   <tag></tag>
   <elementGuidId>235ff14f-30d9-4c40-8667-f787af74a958</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframePage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iframePage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>4c4fdeb6-d4db-43fb-b6e5-152efceac1d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframePage</value>
      <webElementGuid>af9663ce-bdd7-4d54-b301-91ea727b1fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>iframePage</value>
      <webElementGuid>4d0c6ed0-9b24-4142-bfe9-eeb33b8aaae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-1060</value>
      <webElementGuid>1c078581-7198-4fe4-a807-2c1ff9508aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>264527a6-bf01-4d25-8702-cc0dca43cbdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://haboom.com/d/deposit_sr</value>
      <webElementGuid>54ad244a-d243-4129-b587-e8ef70db1001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bis_depth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>04099d38-294d-4b29-9717-91b163570863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bis_chainid</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c0a4f2f2-3d55-4db6-a661-dcae9ce98254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>d4ff7c76-2a9a-469b-80db-9a4a6d1d15a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>resizeIframe(this)</value>
      <webElementGuid>f4db78eb-99fc-4cbd-a759-e94d801ee8bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframePage&quot;)</value>
      <webElementGuid>76d2f616-6cfd-4b08-a805-0547580d38a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframePage']</value>
      <webElementGuid>f4fa8a1c-e192-4997-9884-76d4c48c40a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mod-iframe-52107']/iframe</value>
      <webElementGuid>72c2e502-6d61-44ed-b059-5ca59bf9d624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>72d8b332-759e-4003-8c93-f42cd3fdaf1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframePage' and @name = 'iframePage' and @src = 'https://haboom.com/d/deposit_sr']</value>
      <webElementGuid>300508b2-fce4-429a-b4ea-55beb8235e9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
