<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sportsbook</name>
   <tag></tag>
   <elementGuidId>c5eb4e70-c2b6-41f2-a52b-1eeb83d63f22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='SPORTSBOOK']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SPORTSBOOK</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c20bc079-98ba-46c2-8507-22b16ebd5edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SPORTSBOOK</value>
      <webElementGuid>c4a889e4-52b5-4a7d-8758-18ddb442a331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://haboom.com/sportsbook/highlight</value>
      <webElementGuid>7d0c4173-9c00-43cc-ae83-fd02387225e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>2fb24a3c-64f6-4088-ab67-f9706f7a460d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sportsbook</value>
      <webElementGuid>04e37a73-7c34-42e5-a97e-0ffb63a53f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtml</name>
      <type>Main</type>
      <value>SPORTSBOOK</value>
      <webElementGuid>e3a1d32d-0f7d-4b94-9a6b-3542d8c7c007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                            Sportsbook </value>
      <webElementGuid>ee8abdf1-7427-43f7-a6c5-93058614aba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SPORTSBOOK&quot;)</value>
      <webElementGuid>4427702b-f2b4-481e-ad8f-822e78adee91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='SPORTSBOOK']</value>
      <webElementGuid>26101835-7488-4289-81d7-2a16edcb12fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ssc-pn']/li[3]/a</value>
      <webElementGuid>e02d17b5-51ac-4242-a64d-723cce632ef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sportsbook')]</value>
      <webElementGuid>3c7891dd-2fe1-4e31-a412-3b1c4323b778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exchange'])[1]/following::a[1]</value>
      <webElementGuid>81567825-d0da-480d-9ac6-06f7bc3fa1c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[2]</value>
      <webElementGuid>de823293-3343-4236-b719-480fadfa07bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Casino'])[1]/preceding::a[1]</value>
      <webElementGuid>f17f55a0-e0b8-46e3-9bcc-e1fe9dd02c20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Casino'])[2]/preceding::a[2]</value>
      <webElementGuid>3897f64e-63c5-4a44-bc17-572233b69d52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sportsbook']/parent::*</value>
      <webElementGuid>65654457-8a6a-4bfc-a9d0-b06badaf638f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://haboom.com/sportsbook/highlight')]</value>
      <webElementGuid>7df0d438-2305-4771-8ff8-74e89146b0e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li[3]/a</value>
      <webElementGuid>41ccf0ca-9f7b-4573-89c2-cf2910e977e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'SPORTSBOOK' and @href = 'https://haboom.com/sportsbook/highlight' and @title = 'Sportsbook' and (text() = '
                                                            Sportsbook ' or . = '
                                                            Sportsbook ')]</value>
      <webElementGuid>cc692642-061e-44d0-9dac-1bc27c4056af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
