<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Today</name>
   <tag></tag>
   <elementGuidId>9fb49539-54c7-4785-8580-022c2a7b7c46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mod-inplaysports-1002']/div[3]/div/div/div/ul/li[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>46be26ca-b204-4903-9058-6a1be5f80372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sbInplayScheduleFilter</value>
      <webElementGuid>696593f0-3c61-42cd-a724-9e0d9ed6ec97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-scheduletype</name>
      <type>Main</type>
      <value>today</value>
      <webElementGuid>a272a4d9-cca8-46de-b219-b55e1db0793e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Today</value>
      <webElementGuid>844db62a-2f1f-47ff-a229-a0a81a80536f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mod-inplaysports-1002&quot;)/div[@class=&quot;list-multipickavb&quot;]/div[@class=&quot;sport-container sport-container-1 football-tab visible&quot;]/div[@class=&quot;section-header-marketchooser&quot;]/div[1]/ul[@class=&quot;cls_sp_filters cl_sp_filters&quot;]/li[@class=&quot;sbInplayScheduleFilter&quot;]</value>
      <webElementGuid>199337bf-054a-4849-869f-219107e7fb4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mod-inplaysports-1002']/div[3]/div/div/div/ul/li[2]</value>
      <webElementGuid>c073cf97-03e8-468f-acd5-cae4b4c43c10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In-Play'])[2]/following::li[1]</value>
      <webElementGuid>9c4b32b0-f6ea-44fa-a6e2-244b02e978bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waterpolo'])[2]/following::li[2]</value>
      <webElementGuid>7a9ba681-e0ad-465b-96ea-7be4c638bcb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tomorrow'])[1]/preceding::li[1]</value>
      <webElementGuid>ada39bd9-3548-4e40-b822-19819c39020f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next 7 days'])[1]/preceding::li[2]</value>
      <webElementGuid>6ddaeb19-0b1a-4d9a-a887-f0edde915e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Today']/parent::*</value>
      <webElementGuid>3d8d11c9-a8b9-4e36-8865-43a00cd1c3d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/ul/li[2]</value>
      <webElementGuid>68cbcdaa-9361-406b-9ba3-032d5d9e2d13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Today' or . = 'Today')]</value>
      <webElementGuid>bc469e28-1b0b-4ffb-a5f2-670421b514b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
