<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_yes</name>
   <tag></tag>
   <elementGuidId>6dfa0d3d-0abd-4afa-8d17-ded150407234</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mod-minimarketview-1056']/div[2]/ul/li/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.runner-name.outcomeDescription</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3fcfa2f6-e3a7-4710-b710-b8545b1a9e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>runner-name outcomeDescription</value>
      <webElementGuid>e23bf491-3ca2-4e11-a211-21fb24baae3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-otname</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>1d74523e-63c4-4aef-8eac-c6051f00a66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>d52f8bfd-ad77-48ec-bc8d-ee3a70eef5a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mod-marketgroups-1091&quot;)/div[@class=&quot;marketgroups-list-container cl_marketgroup&quot;]/div[2]/div[@class=&quot;updated-minimarkets cls_evtdetails&quot;]/div[@class=&quot;list-minimarkets ui-inplay ui-event mainContentsBox eventBlock_srmatch47969991&quot;]/div[@id=&quot;mod-minimarketview-1056-container&quot;]/div[@id=&quot;mod-minimarketview-1056&quot;]/div[@class=&quot;minimarketview-content minimarket-MATCH_ODDS-286580488 ui-market ui-market-open cls_et_details cl_ui-market&quot;]/ul[@class=&quot;runner-list3 minimarketview-1056 sb_all_outcome_container kssrr___ext&quot;]/li[@class=&quot;runner-item sb_outcome_box sb-odm accept_tickets&quot;]/span[@class=&quot;runner-name outcomeDescription&quot;]</value>
      <webElementGuid>0c347229-e542-404c-880a-2a4d563dd553</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mod-minimarketview-1056']/div[2]/ul/li/span</value>
      <webElementGuid>36f680b7-d3bd-4e61-8d05-d92cfcd245d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In-Play'])[2]/following::span[1]</value>
      <webElementGuid>01503dfd-3db3-4e1a-8459-eccc5d408b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Will Go In-Play'])[1]/following::span[2]</value>
      <webElementGuid>fdd1a83a-eced-4c21-afaf-2ab6a90dddad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/preceding::span[2]</value>
      <webElementGuid>8844172a-c3f7-432f-a480-90a9ee3e9af9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='no'])[1]/preceding::span[3]</value>
      <webElementGuid>48ca3668-979b-4e0c-bb95-3bf1b6c3af4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='yes']/parent::*</value>
      <webElementGuid>6410a926-9960-4cc2-925b-8fa66a831128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/span</value>
      <webElementGuid>22e41c23-6221-4cb3-be3a-e0c34044ac37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'yes' or . = 'yes')]</value>
      <webElementGuid>26d80cc4-79b5-4815-9cdf-484be0f8e4bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
