<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Cricket_menu</name>
   <tag></tag>
   <elementGuidId>5971aa93-8572-426d-aaad-951833414ae0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.subnav-link.mod-link.ng-binding.cls_cricketHeader</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='subnav']/div/ul/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>86a2b76d-c8c8-4913-8d92-c1957b9afb30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>subnav-link mod-link ng-binding cls_cricketHeader </value>
      <webElementGuid>729fa478-9578-4ebb-ae4a-4ce78f01f0ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://haboom.com/d/exchange/event/4</value>
      <webElementGuid>67327c21-74f5-489c-8d85-31390451bcef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cricket</value>
      <webElementGuid>540a72cd-5657-4e4d-8706-d58f77778d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subnav&quot;)/div[@class=&quot;load-screen ng-animate-enabled ng-scope&quot;]/ul[@class=&quot;subnav ng-scope&quot;]/li[@class=&quot;ng-scope&quot;]/a[@class=&quot;subnav-link mod-link ng-binding cls_cricketHeader&quot;]</value>
      <webElementGuid>1f792b31-f6ee-404e-af4a-d2d3070fd257</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subnav']/div/ul/li[5]/a</value>
      <webElementGuid>5242e54c-c5b2-4fe4-825c-67bca4ba582c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cricket')]</value>
      <webElementGuid>57966381-1290-4387-9fba-e82d0c5e32cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Horse Racing'])[1]/following::a[1]</value>
      <webElementGuid>8421475e-957e-470c-9f0b-ebe5b79d3d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Football'])[1]/following::a[2]</value>
      <webElementGuid>352f440a-7165-4da5-831c-c9219c197549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tennis'])[1]/preceding::a[1]</value>
      <webElementGuid>45ad087d-69ca-40a1-8214-99b03aa1aaee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promotions'])[1]/preceding::a[2]</value>
      <webElementGuid>7dc02af0-d66f-492a-8df5-e54f241b3ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cricket']/parent::*</value>
      <webElementGuid>e7bcf03b-55e2-41db-a5ca-fc58eb2f4c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://haboom.com/d/exchange/event/4')]</value>
      <webElementGuid>64bdc352-9c62-421e-a565-2f394bbfe79f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//bf-sub-nav/div/div/ul/li[5]/a</value>
      <webElementGuid>b55a2b4a-f100-488e-942f-300a8889e9bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://haboom.com/d/exchange/event/4' and (text() = 'Cricket' or . = 'Cricket')]</value>
      <webElementGuid>77d81873-1eff-43ac-86fb-df847442a409</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
