<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Exchange_menu</name>
   <tag></tag>
   <elementGuidId>a81d48e4-377b-4ff3-9ac4-562bd3d26772</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EXCHANGE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='EXCHANGE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>38d553c6-2570-4679-b892-0e5072ef1f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EXCHANGE</value>
      <webElementGuid>e0dce131-c930-487c-80ad-c7dca374166c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://haboom.com/d/exchange</value>
      <webElementGuid>b081ecc0-15c3-47cf-bb3c-5bc7bc575247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>f3dcd01a-8768-4713-85e0-573dee897114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Exchange</value>
      <webElementGuid>90b08446-569f-468a-a2e4-61529d47fe37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtml</name>
      <type>Main</type>
      <value>EXCHANGE</value>
      <webElementGuid>4a46ab9c-fd4c-4cc6-ad92-c42727304e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                               Exchange
                                                            </value>
      <webElementGuid>dcfb5c14-5024-4e0b-b11d-df126719c2a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EXCHANGE&quot;)</value>
      <webElementGuid>b7f15d59-94b5-4d49-8790-141a282d2816</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='EXCHANGE']</value>
      <webElementGuid>a1dc04c8-c149-4158-8bc4-fe8233ec8bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ssc-pn']/li[2]/a</value>
      <webElementGuid>4cf29273-5ed9-4b56-a584-8aab8e715f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Exchange')]</value>
      <webElementGuid>5e7c6994-28f1-4c5f-830d-75ccf1f07ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>71ad3d9d-c931-422f-9bfc-f4191165cd64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sportsbook'])[1]/preceding::a[1]</value>
      <webElementGuid>2298fee7-5689-45e6-9615-2a7ea92e6285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Casino'])[1]/preceding::a[2]</value>
      <webElementGuid>bb0fdbaa-5bbc-4e31-a5c7-530c2bc7eb11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Exchange']/parent::*</value>
      <webElementGuid>cb7f4f32-d801-47f7-8dd5-55f9df4574cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://haboom.com/d/exchange')])[2]</value>
      <webElementGuid>db325b92-90da-4dad-a9d4-db794ad8db94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li[2]/a</value>
      <webElementGuid>6cf5207e-e00f-482b-9e6e-c4c07530d7b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'EXCHANGE' and @href = 'https://haboom.com/d/exchange' and @title = 'Exchange' and (text() = '
                                                               Exchange
                                                            ' or . = '
                                                               Exchange
                                                            ')]</value>
      <webElementGuid>346d2481-c449-4891-b1cd-e02a365c1223</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
