<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Football_menu</name>
   <tag></tag>
   <elementGuidId>6ca734b4-eaef-415e-be42-c3c95e775b89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='subnav']/div/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9be1cde1-3302-47f5-9b02-816889549c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>subnav-link mod-link ng-binding cls_footballHeader  </value>
      <webElementGuid>eb568f9f-e247-4848-92dd-94ee720c0917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://haboom.com/d/exchange/event/1</value>
      <webElementGuid>c848645b-b537-45e8-bdf4-7bcc0bbe29e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Football</value>
      <webElementGuid>d69cdfcd-25c6-449c-9172-d9a8e782400e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subnav&quot;)/div[@class=&quot;load-screen ng-animate-enabled ng-scope&quot;]/ul[@class=&quot;subnav ng-scope&quot;]/li[@class=&quot;ng-scope&quot;]/a[@class=&quot;subnav-link mod-link ng-binding cls_footballHeader&quot;]</value>
      <webElementGuid>b72c094f-f0d0-451c-9b51-0045b1f43b00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subnav']/div/ul/li[3]/a</value>
      <webElementGuid>d01dd724-4533-4ee7-afb6-3e4e152da201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Football')]</value>
      <webElementGuid>938bbc86-e36d-4c60-95c8-54561f6dca50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In-Play'])[1]/following::a[1]</value>
      <webElementGuid>b65a31bc-1367-4449-ba38-d8c1840a1d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/following::a[2]</value>
      <webElementGuid>74b122db-8b6d-49b5-b44a-8dfacdadce98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Horse Racing'])[1]/preceding::a[1]</value>
      <webElementGuid>2e4495d0-aca9-46c2-96a3-250103167685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cricket'])[1]/preceding::a[2]</value>
      <webElementGuid>c21c380a-14e1-4763-9309-4ff8808a57eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Football']/parent::*</value>
      <webElementGuid>131aa8f7-0f06-44af-a995-65f791dba256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://haboom.com/d/exchange/event/1')]</value>
      <webElementGuid>b2f93d4e-e1e0-4cba-9ae4-3e19a8fec167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//bf-sub-nav/div/div/ul/li[3]/a</value>
      <webElementGuid>cc781ade-8265-47a3-8edf-aae5d491595f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://haboom.com/d/exchange/event/1' and (text() = 'Football' or . = 'Football')]</value>
      <webElementGuid>2d603b8e-186e-47d4-893c-3314b1814f9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
