<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>oddvalue_field</name>
   <tag></tag>
   <elementGuidId>ebfe4bd9-13dd-40e4-9827-baca341bfbe2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='odds']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;odds&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f755caa-a85c-4175-a5ed-73b023b3d7c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cca071e3-7f23-40f0-9aec-17cfcd55a445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-step</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>347633ec-e706-41a1-9100-ad8176636519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>betslip-price-ladder__input ng-pristine ng-valid ng-not-empty ng-valid-maxlength ng-touched</value>
      <webElementGuid>e60a8766-c26c-4c1b-878c-2f7192293eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>odds</value>
      <webElementGuid>69c1ab0e-c99e-49da-8e6e-1f5198ec19ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>32657b91-71bd-46ca-8001-1a5859988800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3.55</value>
      <webElementGuid>f587931b-83f4-4c24-85f0-3e0ea48adaa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>e397be17-bfa8-4f05-8888-e0f64277f1ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;placeBet_&quot;)/betslip-potential-bet[1]/section[@class=&quot;betslip__potential-bet--back&quot;]/betslip-editable-bet[1]/section[@class=&quot;betslip__editable-bet&quot;]/div[@class=&quot;betslip__editable-bet__container&quot;]/div[@class=&quot;betslip__editable-bet__item betslip__editable-bet__cell&quot;]/betslip-price-ladder[1]/div[@class=&quot;betslip-price-ladder&quot;]/input[@class=&quot;betslip-price-ladder__input ng-pristine ng-valid ng-not-empty ng-valid-maxlength ng-touched&quot;]</value>
      <webElementGuid>eed6f2ff-68a6-432a-85c8-560c19c82209</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='odds']</value>
      <webElementGuid>afe51e1b-4463-4b8c-83c0-d25dffe7d12a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='placeBet_']/betslip-potential-bet/section/betslip-editable-bet/section/div[2]/div/betslip-price-ladder/div/input</value>
      <webElementGuid>af0888e9-4b3b-4d33-b875-fe82547a5c00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//betslip-price-ladder/div/input</value>
      <webElementGuid>bbba54c0-d05f-42a9-a48f-bf3512c46699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'odds']</value>
      <webElementGuid>97b7ec53-c9e5-470f-931d-4b37b3aa5ba2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
