<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Placebet_button</name>
   <tag></tag>
   <elementGuidId>8e609560-9f5c-4c32-ad10-2bd082abf581</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='placeBet__']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#placeBet__</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d3503aff-058f-4366-b8de-bc3231245e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1d8c180a-542c-4f39-b469-cdbafbd4f73f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_37j6E _2va2z _1J2hg yrTTP oC71t placeBet__</value>
      <webElementGuid>142e8c85-bded-4b23-9b4b-9eedab00abaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>26</value>
      <webElementGuid>4c7dc7ae-ea6e-4404-8b83-523bb9b64657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>placeBet__</value>
      <webElementGuid>5ce90b54-00fb-4e3e-9932-8ca2ee90de9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Place bets</value>
      <webElementGuid>88d4485e-569b-4410-946c-6011f3169525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;placeBet__&quot;)</value>
      <webElementGuid>96ee1316-2bfa-48f8-8518-65d5b8fbb018</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='placeBet__']</value>
      <webElementGuid>2f028f6b-295b-45e0-8bb0-e4ee472fc174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='placeBet_']/betslip-potentials-footer/footer/div[2]/div/ours-button/button</value>
      <webElementGuid>64a99ed8-63be-4509-9331-7ed02742e949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel all selections'])[1]/following::button[1]</value>
      <webElementGuid>035d3c44-baf8-4749-9772-9f5ca08551f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Liability'])[27]/following::button[2]</value>
      <webElementGuid>18697940-277f-44a4-820e-44c35556f906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/preceding::button[1]</value>
      <webElementGuid>9bd6bb96-4395-49eb-bbe4-261b95c6d687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ours-button/button</value>
      <webElementGuid>2ff07c73-c68a-459a-9cca-ed96cdc0ca58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'placeBet__' and (text() = 'Place bets' or . = 'Place bets')]</value>
      <webElementGuid>d93b9e29-9003-4763-b48f-8241bda8e798</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
