<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sportsbook</name>
   <tag></tag>
   <elementGuidId>75662c55-0938-4ef2-9830-fdce3c30254c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='SPORTSBOOK']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SPORTSBOOK</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>76b858f8-0724-4c1b-9429-93aeed72009a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SPORTSBOOK</value>
      <webElementGuid>21d95dea-77a5-481e-8cc9-2286705602ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://haboom.com/sportsbook/highlight</value>
      <webElementGuid>e932db73-9985-4807-930f-56ea4a6ea3cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>c4120708-ba21-45d8-8bdc-3bc2bccb030f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sportsbook</value>
      <webElementGuid>942dc442-04ad-45e1-bb8b-24c199f18a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtml</name>
      <type>Main</type>
      <value>SPORTSBOOK</value>
      <webElementGuid>94eeac0c-471c-42e0-8852-bb8c96805bba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                            Sportsbook </value>
      <webElementGuid>c936aefd-588e-491c-b550-42cdcf8f12cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SPORTSBOOK&quot;)</value>
      <webElementGuid>b9fc4837-bc26-4582-93e2-c117652deca7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='SPORTSBOOK']</value>
      <webElementGuid>f1733cba-8647-44a4-b6aa-f6b5c2a1ba6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ssc-pn']/li[3]/a</value>
      <webElementGuid>62b6dc7d-86e5-472b-97e1-4d76992c165b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sportsbook')]</value>
      <webElementGuid>63424131-0153-41ee-a9ac-449f87f8a36f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exchange'])[1]/following::a[1]</value>
      <webElementGuid>c2de2aa6-2356-44a9-bdec-389975f706fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[2]</value>
      <webElementGuid>86586f0a-1502-4503-b67a-7aad787d92c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Casino'])[1]/preceding::a[1]</value>
      <webElementGuid>0c065723-0db9-43c9-9865-5350d2fb9393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Casino'])[2]/preceding::a[2]</value>
      <webElementGuid>dd9acebe-25b2-4b0c-99c5-02bbfac3b586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sportsbook']/parent::*</value>
      <webElementGuid>b8795d68-7690-4d6f-ac7f-aff9cdcc78c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://haboom.com/sportsbook/highlight')]</value>
      <webElementGuid>b6792413-dbb9-46dd-bf59-a6cfefc96e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li[3]/a</value>
      <webElementGuid>c5fc0b68-5e31-4a6b-9fbe-962a08c32594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'SPORTSBOOK' and @href = 'https://haboom.com/sportsbook/highlight' and @title = 'Sportsbook' and (text() = '
                                                            Sportsbook ' or . = '
                                                            Sportsbook ')]</value>
      <webElementGuid>b20a559f-5049-4172-b088-88258dc45522</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
