<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Help_submitLogForm</name>
   <tag></tag>
   <elementGuidId>d311bdf2-6679-4e07-bf56-c980c1865880</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='submitLogForm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#submitLogForm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>50edbc8f-a3d8-4726-bcb4-5cc620597417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>99304054-8714-46ae-810d-f8c77e6a24a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>head_login</value>
      <webElementGuid>eb87b32b-113b-40f0-b956-0e8012db08de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ssc-cta ssc-cta-simple</value>
      <webElementGuid>ffd5c1a0-c1f7-4cd3-a42a-23976b52bb59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Log In</value>
      <webElementGuid>eb841242-2cdd-4345-872d-51347e0a784f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>checkLogin(this)</value>
      <webElementGuid>d0ec06cb-2f3f-4ec4-aace-5a0ceee7ab27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submitLogForm</value>
      <webElementGuid>decf9ac3-bbd2-43d0-8ba0-ce759b245cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submitLogForm&quot;)</value>
      <webElementGuid>622f7419-0fe7-4650-be60-cacfc7224eb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='submitLogForm']</value>
      <webElementGuid>8040bb98-3b73-4082-a13f-5558cbfc6ed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='head_login']/div[2]/input</value>
      <webElementGuid>46bddeda-e2cd-4d9c-b062-c1246df6db52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>4f58f2d4-d851-4592-934e-1fb15a716198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'submitLogForm']</value>
      <webElementGuid>9d75bdd6-fea6-478c-a66c-ebf011992ccd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
