<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Password_password_show</name>
   <tag></tag>
   <elementGuidId>996ef469-c57a-455b-bb1a-c411b493443d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#password_show</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='password_show']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3c062ad5-6540-4410-8013-26671ee93201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-eye icon-hide-pass</value>
      <webElementGuid>727d10a7-7cfa-48e3-80da-f48cc93c38dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password_show</value>
      <webElementGuid>4d79a5fd-c28f-455d-8827-375801a5572e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password_show&quot;)</value>
      <webElementGuid>13a9d2f3-7ba1-4310-ac4d-32b0f0616426</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='password_show']</value>
      <webElementGuid>823aee68-e26d-4389-960b-a2d7b7e458d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginForm']/fieldset/div[2]/div[2]/span</value>
      <webElementGuid>a07f403e-ed0a-4dd2-a645-2fc4493dfff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>96ec6469-7a79-4cca-9eef-0794dd1ded19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'password_show']</value>
      <webElementGuid>c2c01447-c065-4a0b-a647-6c30fa87353d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
