<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>My Account</name>
   <tag></tag>
   <elementGuidId>39b3e173-81a4-4c7e-8a97-0c7f611b56da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ssc-un</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='acco_arr']/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>26515023-ed94-4707-a698-a0fccdac2683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ssc-un</value>
      <webElementGuid>baa5f125-27bf-4bc4-acf2-bd8cc2d8bcc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Account</value>
      <webElementGuid>6ce615db-ea24-4a2f-aa77-fa1e8591baa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acco_arr&quot;)/a[@class=&quot;ssc-unc&quot;]/span[@class=&quot;ssc-un&quot;]</value>
      <webElementGuid>e065a691-206c-4fac-8dbf-5b85347093c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='acco_arr']/a/span</value>
      <webElementGuid>30d4fa6e-2d4d-4db3-881e-ef21bc3b80cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/following::span[4]</value>
      <webElementGuid>12a02426-4bd8-496b-8e72-f59101092bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Bets'])[1]/following::span[4]</value>
      <webElementGuid>576dc713-5958-498a-ad00-a4401f76d36d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My Account']/parent::*</value>
      <webElementGuid>8a709384-3747-4c2a-aed2-bbfe06686fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/a/span</value>
      <webElementGuid>3de607b6-0577-4ac1-85dd-250e8f1feef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'My Account' or . = 'My Account')]</value>
      <webElementGuid>c6b3114b-ce90-45e9-b629-a9a13cc6bcc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
