<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Amount input field</name>
   <tag></tag>
   <elementGuidId>dd9ef651-7a7d-4320-afc8-ba8e8b65144c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#depositamount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='depositamount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>101f0e06-ed0f-4c55-b1f7-5ca97d70a8cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>d50641c6-f6f2-4b53-8abb-81c202495bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>b7d59ca7-004e-46b0-aacd-1720a8dbc263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>depositamount</value>
      <webElementGuid>764aa556-5b46-43d8-a415-06f39cf7dc52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>amount open_amount_input</value>
      <webElementGuid>b1c306f3-4f99-41d8-8074-d379449d622a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>ba8d029a-afd3-4950-b041-2dc3ca0c6711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>validateNumberLatest(this)</value>
      <webElementGuid>5e70cbbe-14ff-435f-bd83-bcc7cd1d9fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>64c8731f-6855-4ffe-881d-94d8e017d8b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item_amount_1</value>
      <webElementGuid>deeafe27-d923-4552-a5bc-a24ad4b20ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;depositamount&quot;)</value>
      <webElementGuid>c37c419f-2af7-4e47-ab15-6442742caaf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/My Account_Payment/Deposit Bank Transfer/Bank transfer page/iframe_Refer and Earn_iframePage</value>
      <webElementGuid>6f83fc52-acbc-4290-b704-0ab25b57e768</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='depositamount']</value>
      <webElementGuid>cc8decad-4556-4131-9a8c-4bdb3e7643a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='amount_section_wrapper']/div[3]/div[3]/div/div/input</value>
      <webElementGuid>6b876cd3-f25b-4ce5-bcc1-56a3f479ac2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>09f947fa-d26a-4fba-a445-85960c330b16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'depositamount' and @name = 'item_amount_1']</value>
      <webElementGuid>0e745f53-caf7-4b5f-baa4-9905253c1112</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
