<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Refer and Earn_content-container</name>
   <tag></tag>
   <elementGuidId>0afcd674-2022-477a-adde-5fb1912d991c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#content-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c3530fab-199a-4349-9ceb-4674bb4372e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>content-container</value>
      <webElementGuid>b63c8fe3-0205-4cef-9279-3be3a8803468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-content-container main-content-desktop-container__page light cls-iframe-cnt</value>
      <webElementGuid>d8ba2191-24a4-419d-850b-841db36d3a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bis_skin_checked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>872e6a06-3f89-47d7-84fb-66fad13d51aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-container&quot;)</value>
      <webElementGuid>4ff8e5c4-7b1d-461d-a900-ad256f83cd29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='content-container']</value>
      <webElementGuid>227fa62a-7815-4fa5-b5b5-c47e99c0c0aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='ssc-header-placeholder']/div[15]</value>
      <webElementGuid>eff9c31c-7de5-4994-8d1a-0d1f6e10dbcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refer and Earn'])[1]/following::div[1]</value>
      <webElementGuid>005b2ad1-1e92-4086-8758-9bb3f9d79c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promotions'])[1]/following::div[1]</value>
      <webElementGuid>0e045d85-3bd5-4c3a-a5c1-84ef13d9dbde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/preceding::div[13]</value>
      <webElementGuid>2e216e65-814d-4c12-88f5-12f1fbd5b49a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[2]/preceding::div[13]</value>
      <webElementGuid>a8a3b131-1f90-48e0-94b4-f95866ca21cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]</value>
      <webElementGuid>6e058ffb-5352-484e-8fbe-542df7ee8c3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'content-container']</value>
      <webElementGuid>e43cbb64-c8f6-49c0-ba09-1c55f40d59f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
