<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Payments</name>
   <tag></tag>
   <elementGuidId>788bbfae-9d7d-499c-8962-9983857543ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.link-group</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='Pay_ment']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>042b48de-7424-4358-b234-90c249fdd0fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link-group</value>
      <webElementGuid>c584d070-af1e-4805-8b8e-3274224a2afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Payments</value>
      <webElementGuid>e66c1084-72f1-4ca3-b807-d48abb82943b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Pay_ment&quot;)/a[@class=&quot;link-group&quot;]</value>
      <webElementGuid>c560d5b0-f51e-4de8-a42a-3aa41fce630e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='Pay_ment']/a</value>
      <webElementGuid>e08595f9-f238-4609-83fb-9bf53b72f9ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Payments')]</value>
      <webElementGuid>5a2395d5-e368-49bb-95c7-3e0c62b0c5f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUMMARY'])[1]/following::a[1]</value>
      <webElementGuid>7e1bfb56-fba8-4f89-9494-ecfd7cf900ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to Betting'])[1]/following::a[2]</value>
      <webElementGuid>1b799ee4-a703-4f9f-a9ae-8e72724c34cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deposit'])[4]/preceding::a[1]</value>
      <webElementGuid>e92029b6-1fb1-428a-9a28-ebb81e9bd718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Withdraw'])[2]/preceding::a[2]</value>
      <webElementGuid>db959338-df8b-48f2-9b89-469588972e83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Payments']/parent::*</value>
      <webElementGuid>e652d2dc-bccd-4c7d-961a-455764ad42a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]/a</value>
      <webElementGuid>ffdf1625-6038-4311-80e8-8e79ef6a909e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Payments' or . = 'Payments')]</value>
      <webElementGuid>f8fd20ea-5eb8-4df1-b972-863485352723</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
