<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UTR Submit button</name>
   <tag></tag>
   <elementGuidId>9d9d8226-f71b-46d4-83da-c7e85d1722e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.submit-button.cls_deposit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>07e233b3-522f-4520-a6a4-797f666fa6f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2d15dd72-3d39-44d9-ae4a-63a5dc0bd610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>de5c976c-9a5b-4e33-8b1d-6c7d9a24e58e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submit-button cls_deposit</value>
      <webElementGuid>cd7e4c6c-4dcd-4beb-9cc5-25ccee0d0871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>ce4d69bf-cbdd-4015-9900-30874de2f5bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;bf en_GB webkit&quot;]/body[@class=&quot;layout-payment-web desktop showHeader international BA en_GB card-deposit cls-layout-payment-web&quot;]/div[@class=&quot;section-toggle-in cls_deposit_con&quot;]/div[@class=&quot;toggle-section&quot;]/div[@class=&quot;toggle-section-in&quot;]/div[@class=&quot;form-section&quot;]/form[@class=&quot;extra-form&quot;]/div[@class=&quot;submit-sec&quot;]/button[@class=&quot;submit-button cls_deposit&quot;]</value>
      <webElementGuid>63e2793c-2bc5-440b-bb1b-7832364abd3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/My Account_Payment/Deposit Bank Transfer/Bank transfer page/iframe_Refer and Earn_iframePage</value>
      <webElementGuid>8d0653b4-b7f6-492a-81df-331e4e31e9c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>db6260e9-74ad-4ee8-9de2-9ffeebf88cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter Reference Number'])[1]/following::button[1]</value>
      <webElementGuid>86c42c68-2f01-44a5-a107-fbb11a65b4e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[1]/following::button[1]</value>
      <webElementGuid>56dd23e4-789d-448c-ae11-68f17722e784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='‹'])[1]/preceding::button[1]</value>
      <webElementGuid>e0e59537-da5f-40e5-922f-fd27928cd4df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='›'])[1]/preceding::button[2]</value>
      <webElementGuid>9b0e9378-e907-4802-92fd-442e6ecb36ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>65f9ca36-8f7c-433e-8814-28da173e0c57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>3e160b8c-9574-4d24-b0f9-df39f5337858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>5a52f375-b379-4edc-aee3-82882d25623e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
