<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Help_submitLogForm</name>
   <tag></tag>
   <elementGuidId>f5e5af40-d306-4c00-846b-dcc575f5a6fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submitLogForm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='submitLogForm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd62026e-42f8-485f-a924-ccad4c67f943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9779a34e-657d-4fe0-81b5-1508f52b6e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>head_login</value>
      <webElementGuid>8259400d-77db-436d-b661-b69d5cf27582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ssc-cta ssc-cta-simple</value>
      <webElementGuid>c13f0a01-fc7b-45ec-9365-dfe12ecd3843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Log In</value>
      <webElementGuid>dac7eee2-d54c-4d54-b779-8c22bd3c2979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>checkLogin(this)</value>
      <webElementGuid>d3d443be-5d9c-4532-b2ca-a9dbaf4b7dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submitLogForm</value>
      <webElementGuid>f0d0b182-f266-4848-80c0-aa691488ce84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submitLogForm&quot;)</value>
      <webElementGuid>1ecbf4a0-fb11-4738-b687-297d5ef2afd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='submitLogForm']</value>
      <webElementGuid>ba38fc43-f4f7-47f6-9ac9-02532ba65906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='head_login']/div[2]/input</value>
      <webElementGuid>2fba0f90-deb6-4a98-8a4a-4cafa1b16301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>cf331886-745c-44c1-a3f5-05c097ca0611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'submitLogForm']</value>
      <webElementGuid>ead710ae-c173-4c03-8151-b69837dad0e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
