<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>To player</name>
   <tag></tag>
   <elementGuidId>f86ea1c7-3c5c-4f5c-8f95-d13d8eaa1ae6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='email__']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#email__</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>781cd016-795b-4bf9-b7a8-6197ec59c066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>8534a296-424b-4397-b978-f1066c26a5b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autofill</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>70be8eec-f60a-49ad-bcaf-51982234817f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>a22c271e-0d22-477e-8a32-9ff20276fbd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email__</value>
      <webElementGuid>47dfe91f-b6b0-4284-9a9d-a7888bfc96de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>035fbe7a-42c8-48e1-a880-6e7e2ebfc784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-12</value>
      <webElementGuid>bc9ceea8-1a37-422a-9933-06574263530a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>9185ce0d-e2e5-42bd-b42f-debf13b769d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter username/email/phone number</value>
      <webElementGuid>33128bbf-4c8f-4cd2-905d-c8b998b9a5f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>if(this.value.indexOf(' ') >= 0) this.value = this.value.replace(' ','');</value>
      <webElementGuid>d873d2b6-db48-4033-847d-c606dd7b3f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ((event.charCode > 64 &amp;&amp; event.charCode &lt; 91) || (event.charCode > 96 &amp;&amp; event.charCode &lt; 123) || event.charCode == 8 || event.charCode == 32 || event.charCode == 46 || event.charCode == 64 || (event.charCode >= 48 &amp;&amp; event.charCode &lt;= 57));</value>
      <webElementGuid>aea7bd22-61c8-4555-960f-09d9ca669123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email__&quot;)</value>
      <webElementGuid>0ae6e598-7c1f-4c07-a66a-6ff67cdfacce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='email__']</value>
      <webElementGuid>8780a97d-5508-4f21-a49e-a657f318d28b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='transfer-section']/div[2]/ul/li[2]/input</value>
      <webElementGuid>857f6259-f9b1-4f8c-8862-e18989e1d880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/input</value>
      <webElementGuid>4cb5e48e-d8d9-4977-b9de-aa63e9765c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'email' and @id = 'email__' and @type = 'text' and @placeholder = 'Please enter username/email/phone number']</value>
      <webElementGuid>82f2372e-6f35-4658-b3d8-7cd405fa63f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
