<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Transfer Password</name>
   <tag></tag>
   <elementGuidId>04be13fb-c107-40bc-b922-a3a765cbaa9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reqpwd']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reqpwd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b55034b1-0665-4799-9703-152ec71a506b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reqpwd</value>
      <webElementGuid>a0c787e3-9a39-4ab6-aef0-4e2c89621529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reqpwd</value>
      <webElementGuid>becde706-5757-43ea-907e-e57b94b4def7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>a9b1e4c7-2177-4dfe-9012-d4a542a3486c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-12</value>
      <webElementGuid>ad7d524a-5058-48cb-bc75-537206ed481a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>68fe0cfc-d238-4d70-95aa-925660352763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>if(this.value.indexOf(' ') >= 0) this.value = this.value.replace(' ','');</value>
      <webElementGuid>efca1808-2998-407a-9c0e-8e6ed1a23a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reqpwd&quot;)</value>
      <webElementGuid>183c5dd4-5063-4fad-9e10-9724a0f9fd14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reqpwd']</value>
      <webElementGuid>c8b4f8cf-c076-4317-82da-4dbf1a2cc175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reqpwdSec']/div/input</value>
      <webElementGuid>bebd6e1c-3f69-4005-94af-596ab09e9841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>61eea35f-8bdc-4756-a2ee-ce0bc5d08f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'reqpwd' and @id = 'reqpwd' and @type = 'password']</value>
      <webElementGuid>b3eeb2f0-7852-4373-8e5d-98e1e268baf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
