<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>transfer amount</name>
   <tag></tag>
   <elementGuidId>ced3aaf0-3b44-4b48-8891-8eb7287929b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='transfer-amount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#transfer-amount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f87e474e-298b-4bd5-b9c5-bc2a0e37ef70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>transfer-amount</value>
      <webElementGuid>0ba4fe4e-915f-48c6-af66-a344695fc2f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transfer-amount</value>
      <webElementGuid>e752aeae-fcf1-4c17-ad24-00ed22e10f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d0dfe027-41f1-4ac1-b600-3f0c2a3cb08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>fe545550-48d5-4139-9917-b12d24a220e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>₹</value>
      <webElementGuid>8a174a32-378a-4c4b-9a6d-f363d7162ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>validateNumberLatest(this)</value>
      <webElementGuid>e2d7c5af-8f9f-4433-80c7-2257cc4fbabb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>0cf3278a-44f6-4c8f-a718-f66bf0189173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transfer-amount&quot;)</value>
      <webElementGuid>918358db-629d-41d3-bd92-95beccb2c27e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='transfer-amount']</value>
      <webElementGuid>3cd282ea-7743-4b80-b146-5ae42eb85a3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='transfer-section']/div[2]/div[2]/ul/li/input</value>
      <webElementGuid>6cadcd14-11e9-4d36-91fc-f7ba51ef9dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>f156e06a-7ea8-48c9-af08-a5fea781050e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'transfer-amount' and @id = 'transfer-amount' and @type = 'number' and @placeholder = '₹']</value>
      <webElementGuid>9564977e-ce88-4c5c-b9f4-f55d8810562e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
