<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cricket</name>
   <tag></tag>
   <elementGuidId>cbc2f522-37ec-46a1-b528-b8b5a264d885</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zone-left-col']/div[2]/div/div/div/li/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>87d682aa-0719-4db5-be35-af8cac4b3114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b01aa31e-44df-4fc6-bec1-7a326e317671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cricket</value>
      <webElementGuid>ff739660-e31e-4361-af4e-9cbd44cc2a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zone-left-main-right&quot;)/div[@class=&quot;grid-1&quot;]/div[@id=&quot;zone-left-col&quot;]/div[@class=&quot;grid-1&quot;]/div[@class=&quot;quicklinks-inner-container&quot;]/div[@class=&quot;quicklinks-section&quot;]/div[@class=&quot;quicklinks-list cls_sp_nameql&quot;]/li[@class=&quot;featured-link cl-featured-link cls_sp_redt gotoInplayDesktop&quot;]/a[@class=&quot;ui-nav ui-top ui-gtm-click-defer&quot;]/span[@class=&quot;label&quot;]</value>
      <webElementGuid>e8c2e624-e4c6-4cd8-b934-163dd5e4e3a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zone-left-col']/div[2]/div/div/div/li/a/span</value>
      <webElementGuid>7a11173c-962e-4ede-ac45-69aa1d586f46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sports'])[1]/following::span[1]</value>
      <webElementGuid>15f18ccf-671e-4a09-81f3-6cce7285577a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soccer'])[2]/preceding::span[2]</value>
      <webElementGuid>1736286b-74fe-48d7-bd04-f73ba2c4526d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tennis'])[2]/preceding::span[4]</value>
      <webElementGuid>ff3e91fb-f31b-4664-b885-5e68b4f4824a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/li/a/span</value>
      <webElementGuid>4dd6dcfe-3543-4b9b-94a2-a3a8e5bb82f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Cricket' or . = 'Cricket')]</value>
      <webElementGuid>ad9481d3-df37-4040-9163-d64d75d4c9ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
