<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OTP</name>
   <tag></tag>
   <elementGuidId>6ed510a2-db4b-4806-aeb7-36583c934bec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#verify_one_timepass</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='verify_one_timepass']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>437ba907-a1c1-47f1-8554-76911db7c76f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>199953eb-0d17-48a6-9bcc-e116bb9e91c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otp</value>
      <webElementGuid>11089e4a-814a-4d22-9d38-7b87abd8e974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>verify_one_timepass</value>
      <webElementGuid>f80daf5f-16b7-4cf6-aeb5-5268251e6321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input validate </value>
      <webElementGuid>a107d2b5-7102-41fc-9e81-44fdfee0a1be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>82dbe5e5-a304-402a-a8f6-8ca681d7e812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\.*?)\.*/g, '$1');</value>
      <webElementGuid>50b05588-f967-44cd-88d4-a1c379d0dd8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verify_one_timepass&quot;)</value>
      <webElementGuid>0178fb41-085c-44b8-ba96-868ebbb0206a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='verify_one_timepass']</value>
      <webElementGuid>fe6f17ef-65a8-4e0e-b068-20344791a06a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='otp_pass']/div/input</value>
      <webElementGuid>b1ceec24-3ce8-4cdf-8884-3630e1e491b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>beb74054-1662-4360-b0bb-6fe3f20e849a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'otp' and @id = 'verify_one_timepass']</value>
      <webElementGuid>e652481a-82d0-48e0-abdd-afee22f2acda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
