<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Exchange Betting History</name>
   <tag></tag>
   <elementGuidId>07b4278f-0c06-432a-a1d1-cbbb520cc33e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='Betting_Activity']/ul/li[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.dropdown-menu > li:nth-of-type(6) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e34d8cc0-167f-4a12-9a96-04a69531c9f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://haboom.com/d/exch_bethistory</value>
      <webElementGuid>e68b0e25-0ef7-4faa-a962-e3a0b412a8b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Exchange Betting History</value>
      <webElementGuid>08c0464e-a765-49c0-bbb6-2c86c55cb1ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Betting_Activity&quot;)/ul[@class=&quot;dropdown-menu&quot;]/li[6]/a[1]</value>
      <webElementGuid>47eb30db-7ae6-4d7e-be92-f3a8beb61005</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='Betting_Activity']/ul/li[6]/a</value>
      <webElementGuid>d32a0c57-8eda-4438-9281-7c6f67af55bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Exchange Betting History')]</value>
      <webElementGuid>ab22d6e6-000b-4e3c-b68b-899cf1a0b6d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exchange Current Bets'])[1]/following::a[1]</value>
      <webElementGuid>03c271ad-03c2-47bb-8402-7352332756bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Slots Bets'])[1]/following::a[2]</value>
      <webElementGuid>903bd0ac-fd2d-473a-a862-66c253b3f66e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exchange Profit &amp; Loss'])[1]/preceding::a[1]</value>
      <webElementGuid>137207a0-52a1-4437-8e15-95ac5b0d383f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tickets'])[1]/preceding::a[2]</value>
      <webElementGuid>35cf8440-37dd-4448-8788-0bd8977d4400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Exchange Betting History']/parent::*</value>
      <webElementGuid>00a85f1e-eba3-4b79-8511-295e9449faae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://haboom.com/d/exch_bethistory')]</value>
      <webElementGuid>422a1439-8a0a-46ba-a8d7-66c11953670c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[6]/a</value>
      <webElementGuid>e314e58b-c9ca-480c-a07f-f5f1b0a58f34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://haboom.com/d/exch_bethistory' and (text() = 'Exchange Betting History' or . = 'Exchange Betting History')]</value>
      <webElementGuid>65e1113c-df55-45f8-98fe-0380effdcda2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
