<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_My Casino Bets</name>
   <tag></tag>
   <elementGuidId>130d132f-9c72-4280-bedb-a43486db93ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='Betting_Activity']/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Betting_Activity > ul.dropdown-menu > li:nth-of-type(3) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>67292333-a81d-46b6-8481-408c9cb917e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://haboom.com/d/casinobethistory</value>
      <webElementGuid>45cd5b93-31e6-4b57-9a6f-8ad98648cc8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Casino Bets</value>
      <webElementGuid>56aef003-dbba-46a6-8e9d-e6536dfeabb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Betting_Activity&quot;)/ul[@class=&quot;dropdown-menu&quot;]/li[3]/a[1]</value>
      <webElementGuid>eb174873-cf4a-442b-9902-7dc46a711b98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='Betting_Activity']/ul/li[3]/a</value>
      <webElementGuid>c164eab1-6b5b-45be-9b2b-8f3f6619bc6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'My Casino Bets')]</value>
      <webElementGuid>32b690eb-9d1f-4115-a023-82955196fd09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sportsbook Betting History'])[1]/following::a[1]</value>
      <webElementGuid>dd66e647-a809-43cd-a2ee-88940e7ab3e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exchange Bets'])[1]/following::a[2]</value>
      <webElementGuid>e3bf3562-8501-4a06-bab4-9f51e519c12c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Slots Bets'])[1]/preceding::a[1]</value>
      <webElementGuid>778c8077-3df1-4266-9e2e-bab2b3c0c1bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exchange Current Bets'])[1]/preceding::a[2]</value>
      <webElementGuid>a302bd33-367d-400a-85ce-44b8442e438f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://haboom.com/d/casinobethistory')])[2]</value>
      <webElementGuid>6431ce53-fee9-4c23-9d8c-1d6013737d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[3]/a</value>
      <webElementGuid>05432df2-4201-4a7e-b4a2-b909f70184f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://haboom.com/d/casinobethistory' and (text() = 'My Casino Bets' or . = 'My Casino Bets')]</value>
      <webElementGuid>546c00f8-10bb-4712-9666-d8b2016d876a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
