<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Account IFSC code</name>
   <tag></tag>
   <elementGuidId>06bb1d3a-1faf-454f-8196-f05e4dffc3ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ifsc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ifsc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ef2f94f-2b63-4414-9f69-b6e51cef495b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d5645b5b-632b-4685-ade0-766341519dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ifsc</value>
      <webElementGuid>77176d47-fc97-4180-b363-6905670e2650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ifsc</value>
      <webElementGuid>bd345207-a2c3-4c85-b774-5feec6c7260e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>IFSC Code</value>
      <webElementGuid>dde408a5-8882-4bc0-8011-14b9464a3a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>677164de-4a10-4ad0-a4ec-27d492c26261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>69e5d36f-4dae-4a9d-9ba4-82d72fdd4610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ifsc&quot;)</value>
      <webElementGuid>140ad1ad-86c9-40f9-b2bc-8d2440454fcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ifsc']</value>
      <webElementGuid>06083fc0-54af-4eb0-971b-f8921bfc840a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_mainContent_wizBankDetailsCapture_tblTemplate1C961B599E89E3119F750050568A2F55']/tbody/tr[5]/td/input</value>
      <webElementGuid>9eacef02-d164-4e3d-a167-d91c4557fd24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/input</value>
      <webElementGuid>6a4b8142-68d6-49ae-9d57-3d4fcc417489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ifsc' and @id = 'ifsc' and @placeholder = 'IFSC Code']</value>
      <webElementGuid>c5b20305-03ad-4b77-be34-693e82c43e45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
