<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Account holder name</name>
   <tag></tag>
   <elementGuidId>4bd964f5-4d84-42ef-96e0-7f3f83864f69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payee_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payee_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a44d2761-389f-4023-a8b3-4b86c4bada96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5f4c1f10-08a2-4d14-94f8-db74268092f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>50ff0db6-e447-4536-b50b-bbcde6534b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payee_name</value>
      <webElementGuid>29fcc4ec-8085-4f13-acb3-f7e73a5347e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Account Name</value>
      <webElementGuid>b47b7ec7-ab39-4692-93fe-672c1ae5b606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5a9d2614-219b-460f-8e7b-ec9c9ab96a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return (event.charCode > 64 &amp;&amp; event.charCode &lt; 91) || (event.charCode > 96 &amp;&amp; event.charCode &lt; 123) || (event.charCode == 32)</value>
      <webElementGuid>fb1400a7-7bd9-4535-98b7-7fcf7593dc64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>1bb04773-5e83-4165-b761-c5dc331ea6f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payee_name&quot;)</value>
      <webElementGuid>400e75df-5ebf-44c4-bb52-498e643a04ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payee_name']</value>
      <webElementGuid>12cdc352-3053-4023-91d4-9e2f009d30c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_mainContent_wizBankDetailsCapture_tblTemplate1C961B599E89E3119F750050568A2F55']/tbody/tr[3]/td/input</value>
      <webElementGuid>677a11c4-2648-4b71-8985-699bca57db86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/input</value>
      <webElementGuid>89310fd9-8e68-4d3d-ac74-48ed8ff855df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'name' and @id = 'payee_name' and @placeholder = 'Account Name']</value>
      <webElementGuid>c0f913ee-57ac-4a87-a6ac-fa900039405f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
