<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Withdraw</name>
   <tag></tag>
   <elementGuidId>497384b4-8e7c-477d-a291-231c1ecf72fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='Pay_ment']/ul/li[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.dropdown-menu > li:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2d6f7842-1431-4942-9a84-63e9965afdcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Withdraw</value>
      <webElementGuid>59bc474d-1b8d-4139-a2d7-7044a721e3f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Pay_ment&quot;)/ul[@class=&quot;dropdown-menu&quot;]/li[2]</value>
      <webElementGuid>e091e0ae-e340-4dd9-81fc-6f8840a8d5fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='Pay_ment']/ul/li[2]</value>
      <webElementGuid>5149481a-33b7-4955-8a3b-40dbeb8a1dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deposit'])[4]/following::li[1]</value>
      <webElementGuid>4a6a0097-5658-43cf-99a3-e922c45fe896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payments'])[1]/following::li[2]</value>
      <webElementGuid>f70f484e-14c8-4bdc-8224-692e2cae9d44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transfer Funds'])[1]/preceding::li[1]</value>
      <webElementGuid>0467f382-dbc8-4534-ac1c-f129eb0ee5f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[2]</value>
      <webElementGuid>a501fb12-c114-4ffc-b646-4ee092e828e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Withdraw' or . = 'Withdraw')]</value>
      <webElementGuid>1b055542-b227-4c6e-ae1a-634e312a0ffd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
