<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Withdraw amount entery field</name>
   <tag></tag>
   <elementGuidId>29996895-33f6-4250-bc77-ee141c43bb63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='amt_field']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#amt_field</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bcdc2628-8dc9-47ab-ba0d-052c1974fe7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>200a8dac-ab6d-46bc-a9b8-348e76321ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub_amount amountValidation cls_withdraw</value>
      <webElementGuid>487ae71c-7330-4586-bc3c-006c3ee8dda0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>amt_field</value>
      <webElementGuid>b6924795-0166-4562-b4ce-0f302d6a3a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if(this.value.length==7) return false;</value>
      <webElementGuid>ab7fbd7a-1193-48b6-aa27-c021371cdcbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amt_field&quot;)</value>
      <webElementGuid>5fad0ab4-2601-4c0d-a991-fe208d17c08b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/My Account_Payment/Withdraw/Withdraw page</value>
      <webElementGuid>3f88a484-5304-473a-a6f9-231ced3c3617</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='amt_field']</value>
      <webElementGuid>e34bbd2f-f6db-473f-a48f-18e0d5a774f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Alternative_c']/div/div[6]/div/div[2]/table/tbody/tr/td[4]/input[2]</value>
      <webElementGuid>a45bc158-8a0d-4fc8-8416-600942260c6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input[2]</value>
      <webElementGuid>29ab9e40-ba39-466e-abfe-38e91247905d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'amt_field']</value>
      <webElementGuid>7f0dd08a-d8b9-4d5f-bf15-c4c155c7daa2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
