<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Help_submitLogForm</name>
   <tag></tag>
   <elementGuidId>bee4bb0e-64cd-4eb6-ab21-8d474df14b98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='submitLogForm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#submitLogForm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24560de0-e73d-49f7-b2ba-0d98ec1559e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d186b63b-af5e-4f78-a21a-0ba8b6ac522c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>head_login</value>
      <webElementGuid>daee3b41-37cf-4b0f-8851-0831ebb3be42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ssc-cta ssc-cta-simple</value>
      <webElementGuid>8ef85806-2c7c-4c02-b231-8ab9654b2319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Log In</value>
      <webElementGuid>e0eecc30-5bbb-40f4-b58f-14fa5b8a16a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>checkLogin(this)</value>
      <webElementGuid>8dc591a1-0a3f-4ec7-9439-212be03e6b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submitLogForm</value>
      <webElementGuid>df65f69a-a8be-4f6f-ab31-ddc8bcd49036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submitLogForm&quot;)</value>
      <webElementGuid>be34a6e9-d4bd-4c83-84b9-d639b0b4792b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='submitLogForm']</value>
      <webElementGuid>31ddc358-ea2a-49af-8e78-1f6bb2e0b171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='head_login']/div[2]/input</value>
      <webElementGuid>760bb339-4eb8-48ee-854e-9d0f982ca29e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>83e6c689-22d4-41e0-971b-cfd532ccf5b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'submitLogForm']</value>
      <webElementGuid>35d01f16-69cc-4c64-b0bf-c519de504089</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
