<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Today</name>
   <tag></tag>
   <elementGuidId>4fc11f9d-800d-4a01-a4ff-6a6c30d3fbec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mod-inplaysports-1002']/div[3]/div/div/div/ul/li[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>e56cf16d-acbb-4081-9db7-ab4660563abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sbInplayScheduleFilter</value>
      <webElementGuid>43d1fc1e-3de3-4e9e-80e3-9e2952d3788c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-scheduletype</name>
      <type>Main</type>
      <value>today</value>
      <webElementGuid>bd01de0a-ecfc-4ae1-9d5d-27378d37293c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Today</value>
      <webElementGuid>2f169825-09ac-438b-965c-81a00549c1e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mod-inplaysports-1002&quot;)/div[@class=&quot;list-multipickavb&quot;]/div[@class=&quot;sport-container sport-container-1 football-tab visible&quot;]/div[@class=&quot;section-header-marketchooser&quot;]/div[1]/ul[@class=&quot;cls_sp_filters cl_sp_filters&quot;]/li[@class=&quot;sbInplayScheduleFilter&quot;]</value>
      <webElementGuid>a400ca28-7241-4e13-ba2e-4d9902e6be27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mod-inplaysports-1002']/div[3]/div/div/div/ul/li[2]</value>
      <webElementGuid>ec85156d-40c2-4d76-86ed-b9187f506b17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In-Play'])[2]/following::li[1]</value>
      <webElementGuid>0b276a02-d1f8-4f74-835d-744c963460ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waterpolo'])[2]/following::li[2]</value>
      <webElementGuid>a3d66a01-feae-41f6-acca-615709ffd8d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tomorrow'])[1]/preceding::li[1]</value>
      <webElementGuid>a7dd4b99-4fd9-45e2-b3a9-e03743d5d79c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next 7 days'])[1]/preceding::li[2]</value>
      <webElementGuid>a407a086-826c-4247-8f74-a4afbf8b043d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Today']/parent::*</value>
      <webElementGuid>14ac36c9-bb96-4156-ae08-b90fdcc4e2ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/ul/li[2]</value>
      <webElementGuid>4373d33d-08d6-4d13-bd89-02f416cfaa13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Today' or . = 'Today')]</value>
      <webElementGuid>d74be124-f3a3-4c00-87c4-b3ad3649de70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
