<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_draw</name>
   <tag></tag>
   <elementGuidId>00d6a16a-e1e7-43d3-98b0-f50f8b1f7f33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mod-minimarketview-1056']/div[2]/ul/li/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.runner-name.outcomeDescription</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ccd43478-48ce-4862-84a3-a6d2fa38eabc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>runner-name outcomeDescription</value>
      <webElementGuid>2bf00d5c-ef52-4874-bd8f-ea1c79fbd146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-otname</name>
      <type>Main</type>
      <value>draw</value>
      <webElementGuid>3ad7e1fd-75ae-4f12-9ebe-dc100ff26e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>draw</value>
      <webElementGuid>ab71766c-73d9-4b80-8b25-928d45b9a490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mod-marketgroups-1091&quot;)/div[@class=&quot;marketgroups-list-container cl_marketgroup&quot;]/div[2]/div[@class=&quot;updated-minimarkets cls_evtdetails&quot;]/div[@class=&quot;list-minimarkets ui-inplay ui-event mainContentsBox eventBlock_srmatch47610585&quot;]/div[@id=&quot;mod-minimarketview-1056-container&quot;]/div[@id=&quot;mod-minimarketview-1056&quot;]/div[@class=&quot;minimarketview-content minimarket-MATCH_ODDS-286580488 ui-market ui-market-open cls_et_details cl_ui-market&quot;]/ul[@class=&quot;runner-list3 minimarketview-1056 sb_all_outcome_container kssrr___ext&quot;]/li[@class=&quot;runner-item sb_outcome_box sb-odm accept_tickets&quot;]/span[@class=&quot;runner-name outcomeDescription&quot;]</value>
      <webElementGuid>9c3f7853-3365-4041-a0b8-9e01b876a17a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mod-minimarketview-1056']/div[2]/ul/li/span</value>
      <webElementGuid>3b1ae002-8c4d-4173-8ab1-afafd72a1718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In-Play'])[2]/following::span[1]</value>
      <webElementGuid>41de6e37-980b-49b8-b7ec-3fc912ba0383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Will Go In-Play'])[1]/following::span[2]</value>
      <webElementGuid>043265b2-cb69-484f-b2b6-58737e6c4c99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/preceding::span[2]</value>
      <webElementGuid>ebe09179-e7b1-4247-8c38-f8859f9ab00b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chiangmai United'])[3]/preceding::span[3]</value>
      <webElementGuid>b02f5156-bac2-44df-b3a2-3c76b5f56740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='draw']/parent::*</value>
      <webElementGuid>14ecf497-9d4a-4058-a502-649819b59bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/span</value>
      <webElementGuid>7449733d-aa2c-460c-9ee5-3491b140931d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'draw' or . = 'draw')]</value>
      <webElementGuid>e1af7d08-3842-4aa9-95cf-b4ce0d9ffd02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
