<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Refer and Earn_iframePage</name>
   <tag></tag>
   <elementGuidId>5df4a6bb-8206-40d8-9d02-5bd9b8f33f65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iframePage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframePage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f8c8ca71-d993-4412-b947-97954fe8578e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframePage</value>
      <webElementGuid>e259d16c-3727-4c98-bf16-ac6e2fde492b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>iframePage</value>
      <webElementGuid>8a10703a-d1f2-44bb-ab1e-ee311bdcd205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-960</value>
      <webElementGuid>02693a1e-69c8-461f-964f-f9a6c1dd4533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>88c093d5-68e1-4f82-8480-51b0807ec97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://haboom.com/d/withdraw_sr</value>
      <webElementGuid>0876d517-619c-48da-a2e1-08c986a5f50e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bis_size</name>
      <type>Main</type>
      <value>{&quot;x&quot;:153,&quot;y&quot;:147,&quot;w&quot;:1213,&quot;h&quot;:960,&quot;abs_x&quot;:153,&quot;abs_y&quot;:147}</value>
      <webElementGuid>55f830e2-c0d5-4aa9-9d26-9fa0ec2e92eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bis_id</name>
      <type>Main</type>
      <value>fr_9vv6olc4kpq90gs4m2gdf4</value>
      <webElementGuid>05b440c9-f914-4687-8fd3-4a95101ccaa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bis_depth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4cef899f-a98f-48d9-bf9c-2e46043f810b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bis_chainid</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>89404730-f5ae-4fa8-9d5a-4c5bdfcb8c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>90398540-1c0f-44c5-9dfe-b98f8eab1426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>resizeIframe(this)</value>
      <webElementGuid>8d1826de-cb84-4a73-af56-f1f06bd192c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframePage&quot;)</value>
      <webElementGuid>aef0f021-25e4-441f-9365-fbb4705df36e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframePage']</value>
      <webElementGuid>ea68e077-1e8b-4454-a89c-af5597a37c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mod-iframe-189705']/iframe</value>
      <webElementGuid>6f8801d6-aa31-4275-8e99-05421c3ebb76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>557e7017-0d4a-4b53-b1fd-1bef71fbeebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframePage' and @name = 'iframePage' and @src = 'https://haboom.com/d/withdraw_sr']</value>
      <webElementGuid>448eb316-6d5f-44d4-973a-c8e76128840f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
