<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter in amount and click on Withdraw to initiate transaction_amt_field</name>
   <tag></tag>
   <elementGuidId>65063e96-10a1-48bb-ab93-bd5f58c8875a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#amt_field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='amt_field']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a7e5919-26f5-4a55-991f-d3cc1e15086d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>f4e1b76e-0fab-4465-b508-44d32e161615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub_amount amountValidation cls_withdraw</value>
      <webElementGuid>08628034-7534-4ec6-acc6-94e558e49b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>amt_field</value>
      <webElementGuid>2cca5b48-24dd-4d42-82f2-220c62ea7b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if(this.value.length==7) return false;</value>
      <webElementGuid>e41809d7-fb20-4337-8bd4-14f772b5d294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amt_field&quot;)</value>
      <webElementGuid>e8f4b3e8-a549-46d5-a1d9-629697af8ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/My Account_Payment/Page_Haboom - Best 1 Indias Online Sports Betting/iframe_Refer and Earn_iframePage</value>
      <webElementGuid>0275cbb3-f752-435f-aefb-68c5e3bf80ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='amt_field']</value>
      <webElementGuid>10545a84-9f94-423a-a29b-60d0f18fe180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Alternative_c']/div/div[6]/div/div[2]/table/tbody/tr/td[4]/input[2]</value>
      <webElementGuid>e754f8a1-2a78-49f8-9274-1e2fd698e635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input[2]</value>
      <webElementGuid>ca4fc5dc-06aa-4757-be0a-ef24f03601e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'amt_field']</value>
      <webElementGuid>c08f59e0-9ef0-4836-b43e-858dd63b240f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
