<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Account number</name>
   <tag></tag>
   <elementGuidId>0be28262-2350-405e-9d3d-eb5907bbaa2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ac_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ac_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>03219c4f-31d6-4f7a-977f-c16eba4c9233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>875e5a92-2b0b-4fcc-95d2-9b166342fda6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ac_number</value>
      <webElementGuid>c16e863f-c372-4271-b6eb-968c3649eeb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ac_number</value>
      <webElementGuid>6ffc2493-9ee4-4dbc-9bc8-b4f4ca398a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Account Number</value>
      <webElementGuid>01c93d37-8e79-488f-9970-1c9e37b3616a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ee466e3e-c2f5-4694-b96e-de05bcba42b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')</value>
      <webElementGuid>6dc0b448-5f6c-4c0c-a89b-90539fea0588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>edb49a40-cd31-4ff0-b9ec-7a89c32ec11f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>58b804f0-feeb-4a64-9db0-89ae4a9d42a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ac_number&quot;)</value>
      <webElementGuid>6b144126-0ab3-4057-adc2-b1b319fabdcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ac_number']</value>
      <webElementGuid>4c1094ac-e091-4912-b37c-4798d6a868f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_mainContent_wizBankDetailsCapture_tblTemplate1C961B599E89E3119F750050568A2F55']/tbody/tr[4]/td/input</value>
      <webElementGuid>36c5870c-a996-470f-aa91-f9265fe557f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/input</value>
      <webElementGuid>23c256b1-cdc7-49b6-96ae-88843debfeee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ac_number' and @id = 'ac_number' and @placeholder = 'Account Number']</value>
      <webElementGuid>eeff9499-6768-4125-a6f7-0930a71b0323</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
