<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Withdraw button</name>
   <tag></tag>
   <elementGuidId>fd3e72e0-8f82-4d32-9433-cc511ef87971</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#withdrawalmodal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='withdrawalmodal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c41b08f9-e29f-4b0d-acd8-90bedb6e7c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7dadb6e1-02ca-4b6a-83ce-06ad50299a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>withdrawalmodal</value>
      <webElementGuid>ec185cd9-e76d-4460-b385-93e95a17d40a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Withdraw</value>
      <webElementGuid>3bf5a386-45fe-4631-9f2a-eb2e1a751eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;withdrawalmodal&quot;)</value>
      <webElementGuid>e301e412-39f9-4135-b203-40858585482a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/My Account_Payment/Withdraw/Page_Haboom - Best 1 Indias Online Sports Betting/Withdraw page</value>
      <webElementGuid>f81305f4-763d-44e6-8e71-0d55b334a095</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='withdrawalmodal']</value>
      <webElementGuid>b1c036ba-3fc8-43ec-8636-997a781c061a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Alternative_c']/div/div[6]/div/div[2]/table/tbody/tr/td[5]/button</value>
      <webElementGuid>e925dd39-a3ba-4731-aac0-846bc03d0858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter in amount and click on Withdraw to initiate transaction'])[1]/following::button[1]</value>
      <webElementGuid>e703e8e7-310e-478a-b706-79d659d1017b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='other_pms'])[1]/following::button[1]</value>
      <webElementGuid>90fe5976-91b1-469c-9a6c-40e4a058305d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::button[1]</value>
      <webElementGuid>e2edf6ee-d93c-4e9d-b364-e3a0ee50ab56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Withdraw']/parent::*</value>
      <webElementGuid>22de059a-efa0-4df5-bfae-874430634dcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>46e0f0c8-3a1c-4e3c-a0e2-ac1acc0374ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'withdrawalmodal' and (text() = 'Withdraw' or . = 'Withdraw')]</value>
      <webElementGuid>70c382b1-4035-46ee-9dcc-8a8d0a029d99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
