<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>My Account</name>
   <tag></tag>
   <elementGuidId>bc22d7ce-4f5c-48f4-b4b8-29bc88b7905f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ssc-aru.ssc-arus.ssc-sprite</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='acco_arr']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0a45354d-0f03-4994-ad42-091ed7351168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ssc-aru ssc-arus ssc-sprite</value>
      <webElementGuid>9d6e77d0-9dd7-4b91-b68a-b5ca44648eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d67738dc-d479-4929-bbbc-f5b6e64d3450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acco_arr&quot;)/span[@class=&quot;ssc-aru ssc-arus ssc-sprite&quot;]</value>
      <webElementGuid>89c00ed4-602a-4ee9-a3f2-a83afd5d073a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='acco_arr']/span</value>
      <webElementGuid>6ab22481-cad2-45a4-b353-a1c618780918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Account'])[1]/following::span[2]</value>
      <webElementGuid>96a183c8-f71e-473b-830b-9232392096ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/following::span[6]</value>
      <webElementGuid>2270b2a4-02bb-40f5-a0dd-c6092b6d196b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>cd4a9b43-d540-4f9c-a793-fb416bcb4090</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
