<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>User name_Field</name>
   <tag></tag>
   <elementGuidId>18d97f28-0b21-4aff-8723-74a90b87b6ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#usr_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='usr_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de8d76d7-4609-4333-86cc-edc6beefa5cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-selector</name>
      <type>Main</type>
      <value>firstName</value>
      <webElementGuid>7a480a82-896f-4d58-b251-890a40672444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-state</name>
      <type>Main</type>
      <value>is-pristine</value>
      <webElementGuid>3713cbbc-a19a-441e-acf7-edebf1a434fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3475cc2a-b8c0-410e-9c04-aef76a8bdd60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dee4d8e6-759e-42b5-85c6-16b42a8fa748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Enter your Username</value>
      <webElementGuid>1ba4133a-cdbf-4902-a7a8-a82b52a2d5e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>usr_name</value>
      <webElementGuid>27b2857b-a2c6-439b-bff4-821611838919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>c6fec77e-d8e5-485a-a276-11845bb9d894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>has-icon</value>
      <webElementGuid>36923981-19be-417c-9598-7ede58e4af70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>33521a66-26d6-421c-9cc6-c7e3b84aa40f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>if(this.value.indexOf(' ') >= 0) this.value = this.value.replace(' ','');</value>
      <webElementGuid>12258537-8e5d-4dc6-98f2-5dc33c2f5828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;usr_name&quot;)</value>
      <webElementGuid>7f1cf30a-de96-444c-b7ef-4f6a808ea124</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='usr_name']</value>
      <webElementGuid>b28815e4-5d3f-412b-aebe-68c6f22c44ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inputWrapper']/div/div/input</value>
      <webElementGuid>c4cc72e8-160f-4a51-9ed1-2da57dfdcb4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>58251844-2a91-46ab-827c-308921944aed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @title = 'Enter your Username' and @id = 'usr_name']</value>
      <webElementGuid>e427cd44-2f36-463e-a12f-71f056412d20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
