<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Exchange_soccer</name>
   <tag></tag>
   <elementGuidId>5378b21e-a735-46b6-b848-c1d633f14b86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#exchange2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='exchange2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>1247862b-e284-4df5-a671-6d8ee74ada91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exchange2</value>
      <webElementGuid>b68bac70-d508-4b38-b4f3-08fbf3a9fd84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>canvas__anim_width-160</value>
      <webElementGuid>774be2f7-d6e5-4f3e-b784-83a0ec0c3483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>307</value>
      <webElementGuid>bd72c9ba-38a0-44a0-9746-0cf26be4d09e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>153</value>
      <webElementGuid>cc93ddd6-8db3-4936-bf79-8a295b084acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exchange2&quot;)</value>
      <webElementGuid>64341385-5796-43e0-8bac-ad1777061c94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='exchange2']</value>
      <webElementGuid>e32f0f34-0da0-4bb3-9d8c-2e4aca21139d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-wrapper']/div/ui-view/div/div/div/div/div/div/div[3]/div[2]/div[2]/canvas</value>
      <webElementGuid>58e16680-0ca2-4038-811e-a314296249f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/canvas</value>
      <webElementGuid>44bd85c1-f111-4d13-b946-9b0843a437fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'exchange2']</value>
      <webElementGuid>8518fb18-d425-4b5e-a616-90c2f17bf8bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
