<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Exchange_cricket</name>
   <tag></tag>
   <elementGuidId>55088868-569d-44ab-a98a-7c89ecf89467</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#exchange1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='exchange1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>16f52715-92a9-41be-8c22-5a7609957c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exchange1</value>
      <webElementGuid>246ccdaa-c538-411b-9d9c-88116719c9a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>canvas__anim_width-141</value>
      <webElementGuid>a72626d2-c178-44e3-a2f2-0e70713b2c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>282</value>
      <webElementGuid>05483112-30fc-4f4d-9915-e9085bb4448c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>141</value>
      <webElementGuid>938bbf97-fe7d-4059-bcd0-1dd0eee08a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exchange1&quot;)</value>
      <webElementGuid>8b0d4462-1b43-4c5d-95f4-2a764f9e7f97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='exchange1']</value>
      <webElementGuid>0f6c1d82-5e85-4c20-b758-85a03b9a12fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-wrapper']/div/ui-view/div/div/div/div/div/div/div[3]/div[2]/div/canvas</value>
      <webElementGuid>28e6518c-5590-4f51-880e-8e95b28b783e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>7958e497-b2d6-492c-88f5-aa5f945775ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'exchange1']</value>
      <webElementGuid>9e83169f-c553-4c13-a4ea-23e7f4722361</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
