<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Footerlink_PrivacyPolicy</name>
   <tag></tag>
   <elementGuidId>3e03744c-be3d-4709-9e4b-8e37c0979596</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mod-footer-25265']/div[3]/div[6]/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c04812f5-128b-4b01-a481-5ae146c81c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://haboom.com/privacyPolicy</value>
      <webElementGuid>a017e13a-1684-4cb0-a731-ac62e6c78f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sscmw width(1000) height(600) autoscroll(true) ssc-privacyPolicy</value>
      <webElementGuid>bfaae832-187b-49b7-a685-a8157a8d3dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Privacy Policy</value>
      <webElementGuid>3d5ce352-a59d-4c03-8f69-78d61be3d73b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtml</name>
      <type>Main</type>
      <value>privacyPolicy</value>
      <webElementGuid>125410de-93dd-4513-a0a1-9e13982a18f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Privacy Policy</value>
      <webElementGuid>7e319ad2-7ba6-46b6-9ca7-0a74c58d746f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mod-footer-25265&quot;)/div[@class=&quot;ssc-fw&quot;]/div[@class=&quot;ssc-flkh&quot;]/ul[@class=&quot;ssc-flnk&quot;]/li[@class=&quot;ssc-lw&quot;]/a[@class=&quot;sscmw width(1000) height(600) autoscroll(true) ssc-privacyPolicy&quot;]</value>
      <webElementGuid>7c19885f-d479-469e-8a85-61412ba0555e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mod-footer-25265']/div[3]/div[6]/ul/li[4]/a</value>
      <webElementGuid>efc7eb1b-cc11-4b9a-aa12-718f5cd4a819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Privacy Policy')]</value>
      <webElementGuid>105ecfb9-ee68-4401-86e1-5c2fa05bea0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Affiliates'])[1]/following::a[1]</value>
      <webElementGuid>d2e2ea25-014c-4125-a26a-339f2dae365b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQs'])[2]/following::a[2]</value>
      <webElementGuid>75c9896f-ee84-4b94-8359-cc217ddd5949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms &amp; Conditions'])[1]/preceding::a[1]</value>
      <webElementGuid>7b6cb804-6513-4da3-9eb1-63213495b69a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[2]/preceding::a[3]</value>
      <webElementGuid>47208df4-2740-41eb-8c75-bd4d1558b4bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Privacy Policy']/parent::*</value>
      <webElementGuid>8f67b25c-e186-4a06-8daa-ae58f6d4b916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://haboom.com/privacyPolicy')]</value>
      <webElementGuid>7b6fc6fa-0409-430c-b27b-d73f89a17124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/ul/li[4]/a</value>
      <webElementGuid>25da0387-a4dd-4f78-a863-d1caf22fc714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://haboom.com/privacyPolicy' and @title = 'Privacy Policy' and (text() = 'Privacy Policy' or . = 'Privacy Policy')]</value>
      <webElementGuid>5742c88d-177a-4cd1-aa69-d40c3f47c0f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
