<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Footerlink_FAQs</name>
   <tag></tag>
   <elementGuidId>60937dc4-f35b-43d3-a1c7-e4bb529cd0e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mod-footer-25265']/div[3]/div[6]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6b4046be-bc5d-4cb1-a9da-8644db055673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://haboom.com/d/faq</value>
      <webElementGuid>4ba730ce-4b50-4114-b007-0a503463cb2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sscmw width(1000) height(600) autoscroll(true) ssc-helpSupport</value>
      <webElementGuid>29b634eb-de64-4e7c-8f19-323607b2dfc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>FAQs</value>
      <webElementGuid>e0f5b5f6-a5fb-42b7-b55b-9d1eb2014477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FAQs</value>
      <webElementGuid>16e99c9d-9002-4904-9bc7-52d8f321d29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mod-footer-25265&quot;)/div[@class=&quot;ssc-fw&quot;]/div[@class=&quot;ssc-flkh&quot;]/ul[@class=&quot;ssc-flnk&quot;]/li[@class=&quot;ssc-lw&quot;]/a[@class=&quot;sscmw width(1000) height(600) autoscroll(true) ssc-helpSupport&quot;]</value>
      <webElementGuid>7ceb8a13-ea18-4a88-83fe-d64560fcad46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mod-footer-25265']/div[3]/div[6]/ul/li[2]/a</value>
      <webElementGuid>9c5b63f1-7877-424a-8327-ee5aaa8d6fab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'FAQs')]</value>
      <webElementGuid>29f774fd-7396-4251-ab2a-8839653b1365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[2]/following::a[1]</value>
      <webElementGuid>b6b8af9f-fa0b-41b2-a2e5-f11b62aaf09b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Here'])[1]/following::a[4]</value>
      <webElementGuid>7ce673ef-f5d5-4118-99e5-10618503b47b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Affiliates'])[1]/preceding::a[1]</value>
      <webElementGuid>0b9d90e0-fe93-4d1c-98a3-24089b92fe1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/preceding::a[2]</value>
      <webElementGuid>a346aa19-cf5d-4221-bb9b-e1a128ac831e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://haboom.com/d/faq')]</value>
      <webElementGuid>edd41841-3115-4da6-9386-38378652ee8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/ul/li[2]/a</value>
      <webElementGuid>87d9faf4-e735-4f00-82bb-26d4a65277d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://haboom.com/d/faq' and @title = 'FAQs' and (text() = 'FAQs' or . = 'FAQs')]</value>
      <webElementGuid>a6fa8edf-5d35-451f-bcaf-306d6abb680d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
