<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Footerlink_Affiliates</name>
   <tag></tag>
   <elementGuidId>5d9417d8-167d-486f-b01d-409764a666ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mod-footer-25265']/div[3]/div[6]/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>67b29ec7-fb52-4a4d-a95c-9dc08d019264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://haboom.com/d/affiliates</value>
      <webElementGuid>e3749f44-dd6d-45bd-962e-958040ad7d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> ssc-marketingAndAffiliates</value>
      <webElementGuid>8aadbfde-9252-498d-8dc1-a739521f01c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Affiliates</value>
      <webElementGuid>8bb0f438-e3bd-4fdc-a11a-4678c166d58b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtml</name>
      <type>Main</type>
      <value>marketingAndAffiliates</value>
      <webElementGuid>a60b802e-510b-4431-8ad7-8ec8026e110f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Affiliates</value>
      <webElementGuid>63cec425-7c84-4bcd-bca0-8792e6f6813c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mod-footer-25265&quot;)/div[@class=&quot;ssc-fw&quot;]/div[@class=&quot;ssc-flkh&quot;]/ul[@class=&quot;ssc-flnk&quot;]/li[@class=&quot;ssc-lw&quot;]/a[@class=&quot;ssc-marketingAndAffiliates&quot;]</value>
      <webElementGuid>5e22408a-ac33-4416-a32c-1f4dbca51c57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mod-footer-25265']/div[3]/div[6]/ul/li[3]/a</value>
      <webElementGuid>2b754c3a-5b47-4dfa-bcc2-53e8d8f1b23d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Affiliates')]</value>
      <webElementGuid>d8d9c2a3-851e-462d-ad77-a8e0bec075fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQs'])[2]/following::a[1]</value>
      <webElementGuid>7ea7158d-6a0c-422d-a192-8d2b13838d95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[2]/following::a[2]</value>
      <webElementGuid>1aaecda2-7d8d-4174-8d03-13e0363808a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/preceding::a[1]</value>
      <webElementGuid>d6801565-72d0-403a-8b6e-73713c49bfc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms &amp; Conditions'])[1]/preceding::a[2]</value>
      <webElementGuid>199d3fd7-1801-4894-8ec9-4d06dcd9c92c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Affiliates']/parent::*</value>
      <webElementGuid>c93a2004-a9a7-4419-b28b-7a04668a0e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://haboom.com/d/affiliates')]</value>
      <webElementGuid>2f7b0308-7e51-4582-9c8b-0d33d3032955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/ul/li[3]/a</value>
      <webElementGuid>b0bdacb3-ca9f-4127-bbf5-77af975da5d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://haboom.com/d/affiliates' and @title = 'Affiliates' and (text() = 'Affiliates' or . = 'Affiliates')]</value>
      <webElementGuid>98046b4a-5a85-4928-b787-856f08de67bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
