<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Top10games_Roulette_image</name>
   <tag></tag>
   <elementGuidId>3d6d0af1-590b-488b-a0ac-e443a191814c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.kd__position-absolute.kd__br-1.kd__shadow-1.kd__right-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-wrapper']/div/ui-view/div/div/div/div/div/div/div[2]/div[4]/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>84c4aea6-4c7b-4eac-9f66-6dbd90dc5178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>4a93f54f-ed1c-451f-8c8a-b16b849df86f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.onerror=null; this.src='/images/rg_img/placeholders/2/top_games.png';</value>
      <webElementGuid>34a3ecbc-8dbf-4c96-a964-8654d43d2f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d2g8jl9s27zu.cloudfront.net/uploads/alt_banners/haboom_landing_top_10_games/roulette_64FAA41B216FB.png</value>
      <webElementGuid>4e5934ba-dda9-4ee7-bac4-c602ad89d7bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Roulette</value>
      <webElementGuid>2eb16684-2ca5-4946-8b0f-3b0f9fb70529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kd__position-absolute kd__br-1 kd__shadow-1 kd__right-0</value>
      <webElementGuid>8ac699ca-6da0-43be-999d-b40f6ececc4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-wrapper&quot;)/div[@class=&quot;container full-width-page scrollable-columns default-min-size-page&quot;]/ui-view[@class=&quot;ng-scope&quot;]/div[@class=&quot;page-content nested-scrollable-pane-parent front-pages ng-scope&quot;]/div[@class=&quot;bf-row no-bottom-gutter scrollable-panes-height-taker height-taker-helper&quot;]/div[@class=&quot;scrollable-panes-wrapper scrollable-panes-wrapper-helper&quot;]/div[@class=&quot;bf-row no-bottom-gutter scrollable-pane content-page-row&quot;]/div[@class=&quot;content-page-center-column homepage-center-column&quot;]/div[@class=&quot;no-bottom-gutter&quot;]/div[@class=&quot;kd__container-fluid kd__bg-col-1 kd__br-2 new_new_game_bg&quot;]/div[@class=&quot;kd__row kd__overflow-x-scroll kd__overflow-y-hidden kd__bg-img-1 kd__pb-50 top10games&quot;]/div[@class=&quot;kd__col casinoLink&quot;]/div[@class=&quot;kd-w-215-px&quot;]/div[@class=&quot;kd__position-relative kd__height__230  plcholder_pos plc_holder_topten_games fst_child&quot;]/img[@class=&quot;kd__position-absolute kd__br-1 kd__shadow-1 kd__right-0&quot;]</value>
      <webElementGuid>06b31d66-55e0-46d5-babd-cedb01d5f44d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-wrapper']/div/ui-view/div/div/div/div/div/div/div[2]/div[4]/div/div/div/img</value>
      <webElementGuid>eb62b23d-8ebf-4911-8666-6b8497831dd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Roulette']</value>
      <webElementGuid>41d50c5c-d8fc-47b3-9a55-63acd61ae687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/img</value>
      <webElementGuid>2a47cf93-f3d3-4e9c-91a9-bf3932683eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d2g8jl9s27zu.cloudfront.net/uploads/alt_banners/haboom_landing_top_10_games/roulette_64FAA41B216FB.png' and @alt = 'Roulette']</value>
      <webElementGuid>ee21b3d9-fd39-4b9c-9d60-3819807be8ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
