<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Forgot Password</name>
   <tag></tag>
   <elementGuidId>763ef51b-34e6-4ee5-acba-2ac6ea434670</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ssc-fp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ssc-fp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0690c11b-b6ea-4e70-bd1c-ce47fe1a9a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://haboom.com/d/forgetpassword</value>
      <webElementGuid>2aff4fcd-d609-4636-a420-e52037215132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_popup</value>
      <webElementGuid>5f3fcab3-1352-445b-b0e5-27f941422ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ssc-fp</value>
      <webElementGuid>fa8470f3-085b-48af-b418-79acac22a6fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ssc-password sscmw width(788) height(500) autoscroll(false)</value>
      <webElementGuid>703c7307-c878-41b9-aac7-1d55d08ca73a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtml</name>
      <type>Main</type>
      <value>forgot your password</value>
      <webElementGuid>51435ba1-8b69-4ad6-951d-6fd67600fd4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forgot Password
                                                                           </value>
      <webElementGuid>218eea16-035f-4c94-bab9-dd1be13699bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ssc-fp&quot;)</value>
      <webElementGuid>7b518b94-2c1c-42af-8236-a06c824e6fd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ssc-fp']</value>
      <webElementGuid>fb424f1e-219a-4fb7-82f7-943da9ca9ece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='head_login']/div[3]/div[2]/a</value>
      <webElementGuid>bfef2345-8731-401a-909f-5abfad8cd8e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Forgot Password')]</value>
      <webElementGuid>e4f49e13-a122-4e06-93fb-81ad12fbfa66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remember me'])[1]/following::a[1]</value>
      <webElementGuid>aa864a31-7908-489c-ad08-3b27954a99e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Forgot Password']/parent::*</value>
      <webElementGuid>f5cff31c-4088-4c18-979f-2ef1b692a541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://haboom.com/d/forgetpassword')]</value>
      <webElementGuid>d90c8f27-b12f-4774-9144-626767319552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/a</value>
      <webElementGuid>2bc9ac79-0780-4530-90f5-ed86afdcb81e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://haboom.com/d/forgetpassword' and @id = 'ssc-fp' and (text() = 'Forgot Password
                                                                           ' or . = 'Forgot Password
                                                                           ')]</value>
      <webElementGuid>0c20c2fb-cdc7-40bc-b902-9254a58bd78b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
