<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Transactions filter</name>
   <tag></tag>
   <elementGuidId>bf498049-f0ed-466a-a02b-96fc9c272486</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filter_by_type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='filter_by_type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>88000493-4a86-4cdc-85f1-e217ad119426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>826755a0-71f4-484d-aefc-9d2730c46f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default dropdown-toggle cls_slct_type</value>
      <webElementGuid>0b92c6f8-957e-4417-8b09-a1fc10483448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter_by_type</value>
      <webElementGuid>142cb898-fbb4-4fd3-885b-ca17212d3727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>All transactions</value>
      <webElementGuid>015de425-5aa0-480c-8106-bec6902868ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9b27fc1d-6675-45ad-81db-3d4f1e0e96c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f848c1f6-bd6c-4d44-a507-ae5137069e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All transactions</value>
      <webElementGuid>9e0b39d4-32be-4e77-ace3-3683a30be474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter_by_type&quot;)</value>
      <webElementGuid>c78551c1-f519-464f-97a3-4417c1b2b5bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='filter_by_type']</value>
      <webElementGuid>68d72bb9-b1aa-4e61-ba2b-4a4a48982ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='trans_details']/div/div/div[2]/button</value>
      <webElementGuid>bd618aca-4f6d-4e80-8758-7e6b9af7e79c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter by transaction type'])[1]/following::button[1]</value>
      <webElementGuid>4fcbd88a-6d24-4306-a6ee-6c41a2c10c48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To'])[1]/following::button[1]</value>
      <webElementGuid>37867df8-d644-4605-8c5c-a6a81832c517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All transactions'])[3]/preceding::button[1]</value>
      <webElementGuid>606f3c65-2451-40c0-b324-1c0874e63cae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deposit'])[5]/preceding::button[1]</value>
      <webElementGuid>0152d724-bff5-4f72-844f-8953fea4a924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/button</value>
      <webElementGuid>16e165b2-dbf1-4b25-9d54-3aa2eac84a8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'filter_by_type' and (text() = 'All transactions' or . = 'All transactions')]</value>
      <webElementGuid>60a63a2f-4d56-4964-ba3f-d6268f2d7732</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
