<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tennis</name>
   <tag></tag>
   <elementGuidId>9ffbe9c1-5e12-483b-a552-e84f9aad3b96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zone-left-col']/div[2]/div/div/div/li[3]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>78731b68-2cb8-46ab-82e2-0a255daa9253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>2893fdf0-4c59-4806-846d-80d64728377e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tennis</value>
      <webElementGuid>ff25b69f-4d55-4f14-9e05-7597223bb007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zone-left-main-right&quot;)/div[@class=&quot;grid-1&quot;]/div[@id=&quot;zone-left-col&quot;]/div[@class=&quot;grid-1&quot;]/div[@class=&quot;quicklinks-inner-container&quot;]/div[@class=&quot;quicklinks-section&quot;]/div[@class=&quot;quicklinks-list cls_sp_nameql&quot;]/li[@class=&quot;featured-link cl-featured-link cls_sp_redt gotoInplayDesktop&quot;]/a[@class=&quot;ui-nav ui-top ui-gtm-click-defer&quot;]/span[@class=&quot;label&quot;]</value>
      <webElementGuid>491893ea-0ba2-4610-b668-ef1a1245a0d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zone-left-col']/div[2]/div/div/div/li[3]/a/span</value>
      <webElementGuid>6c95c206-6e50-42ca-9784-9e428ba81256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soccer'])[2]/following::span[2]</value>
      <webElementGuid>361d7e9f-74fb-4e97-b8f9-b1caa2269784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cricket'])[2]/following::span[4]</value>
      <webElementGuid>4ad3023f-ccd0-4d11-ac89-8f8e2039a43c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basketball'])[2]/preceding::span[2]</value>
      <webElementGuid>90c6651a-c540-4f22-ad8e-e5c14d3fcff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rugby'])[2]/preceding::span[4]</value>
      <webElementGuid>fd3f18be-9c77-49f8-bc82-07c9fe53e3ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/li[3]/a/span</value>
      <webElementGuid>dfc7047e-bc03-480d-a0c7-a483d9adfff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Tennis' or . = 'Tennis')]</value>
      <webElementGuid>249606a7-5fe2-41b4-8ef0-e96495508224</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
