<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Today</name>
   <tag></tag>
   <elementGuidId>17bcad7f-4543-4996-9ce1-99d415004acb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mod-inplaysports-1002']/div[3]/div/div/div/ul/li[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>7355dbf3-59f3-43fb-9d53-cbccdc319713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sbInplayScheduleFilter</value>
      <webElementGuid>7fda702d-fa8f-4f61-8093-cbed09b313de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-scheduletype</name>
      <type>Main</type>
      <value>today</value>
      <webElementGuid>b06518a3-e87e-436e-97be-8e3bbc06cc61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Today</value>
      <webElementGuid>ac466fa4-b24d-43a0-8285-178fa8b5c92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mod-inplaysports-1002&quot;)/div[@class=&quot;list-multipickavb&quot;]/div[@class=&quot;sport-container sport-container-1 football-tab visible&quot;]/div[@class=&quot;section-header-marketchooser&quot;]/div[1]/ul[@class=&quot;cls_sp_filters cl_sp_filters&quot;]/li[@class=&quot;sbInplayScheduleFilter&quot;]</value>
      <webElementGuid>98330bcc-975b-4600-8173-b381767c6dc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mod-inplaysports-1002']/div[3]/div/div/div/ul/li[2]</value>
      <webElementGuid>facdd68e-c6cd-4441-92b9-281073a0ddca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In-Play'])[2]/following::li[1]</value>
      <webElementGuid>17a48893-be3b-46a4-b960-98372432807d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waterpolo'])[2]/following::li[2]</value>
      <webElementGuid>d0765852-2475-491d-b799-98fd45d6cce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tomorrow'])[1]/preceding::li[1]</value>
      <webElementGuid>809906ed-7d12-421c-a7a0-4f31eea85f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next 7 days'])[1]/preceding::li[2]</value>
      <webElementGuid>14247cc0-e22a-4717-972f-8e69348edcae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Today']/parent::*</value>
      <webElementGuid>0b33c5be-d369-4dbe-bcff-c3c45889faa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/ul/li[2]</value>
      <webElementGuid>24b750e2-dd49-472d-afdb-2f76d9b1eddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Today' or . = 'Today')]</value>
      <webElementGuid>2e49cdf6-e8e7-48f2-92d6-396a5318337c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
