<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Transaction_failure</name>
   <tag></tag>
   <elementGuidId>9ca49523-dbe0-4541-a382-9603a68f6303</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='failure']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;failure&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31c375e7-a5c1-49fe-99ca-6e68bfe0b188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d75cfa0f-f99a-48e8-a117-ef9f95f9a118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>failure</value>
      <webElementGuid>3f2d3c5a-a610-43c0-9dc3-502bb8284070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Generate a Fail Transaction</value>
      <webElementGuid>ea1f8a58-b5a0-49e7-a4e8-c24951e5e913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setFailure();</value>
      <webElementGuid>202b6b8f-ae6f-4cbb-8f1b-6154ca7a6a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/form[1]/table[1]/tbody[1]/tr[4]/td[1]/input[2]</value>
      <webElementGuid>7e42cb51-783c-484b-8980-3d84ecfb6709</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='failure']</value>
      <webElementGuid>e476299d-9fa5-4cce-8ae2-7decc24519cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>18a2958d-0235-4c1c-8fc0-c3f5751d8713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'failure']</value>
      <webElementGuid>8e6cddf5-5563-4550-a316-0ec995d41bc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
